///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ApdRequestModelDataDetailPermintaan {
  /*
{
  "id": "01jyjjy7bzkv0hh2csc7fb3q5f",
  "apd_name": "SEPATU APD",
  "apd_id": "01jx6tpxkwghf6gp62sq27ng64",
  "qty_available": 2
} 
*/

  String? id;
  String? apdName;
  String? apdId;
  int? qtyAvailable;

  ApdRequestModelDataDetailPermintaan({
    this.id,
    this.apdName,
    this.apdId,
    this.qtyAvailable,
  });
  ApdRequestModelDataDetailPermintaan.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    apdName = json['apd_name']?.toString();
    apdId = json['apd_id']?.toString();
    qtyAvailable = json['qty_available']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['apd_name'] = apdName;
    data['apd_id'] = apdId;
    data['qty_available'] = qtyAvailable;
    return data;
  }
}

class ApdRequestModelData {
  /*
{
  "id": "01jyjjy7bvmy2f9qes41ym4wcc",
  "created_at": "25/06/2025",
  "code": "033/REQ/K3L-MKP/VI/2025",
  "unit_name": "Kantor Pusat",
  "doc_status": "2",
  "description": "adaada",
  "longitude_latitude": "null",
  "doc_date": "25/06/2025 00:00",
  "detail_permintaan": [
    {
      "id": "01jyjjy7bzkv0hh2csc7fb3q5f",
      "apd_name": "SEPATU APD",
      "apd_id": "01jx6tpxkwghf6gp62sq27ng64",
      "qty_available": 2
    }
  ]
} 
*/

  String? id;
  String? createdAt;
  String? code;
  String? unitName;
  String? docStatus;
  String? description;
  String? latitude;
  String? longitude;
  String? docDate;
  List<ApdRequestModelDataDetailPermintaan?>? detailPermintaan;

  ApdRequestModelData({
    this.id,
    this.createdAt,
    this.code,
    this.unitName,
    this.docStatus,
    this.description,
    this.latitude,
    this.longitude,
    this.docDate,
    this.detailPermintaan,
  });
  ApdRequestModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    createdAt = json['created_at']?.toString();
    code = json['code']?.toString();
    unitName = json['unit_name']?.toString();
    docStatus = json['doc_status']?.toString();
    description = json['description']?.toString();
    latitude = json['latitude']?.toString();
    longitude = json['longitude']?.toString();
    docDate = json['doc_date']?.toString();
    if (json['detail_permintaan'] != null) {
      final v = json['detail_permintaan'];
      final arr0 = <ApdRequestModelDataDetailPermintaan>[];
      v.forEach((v) {
        arr0.add(ApdRequestModelDataDetailPermintaan.fromJson(v));
      });
      detailPermintaan = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['created_at'] = createdAt;
    data['code'] = code;
    data['unit_name'] = unitName;
    data['doc_status'] = docStatus;
    data['description'] = description;
    data['latitude'] = latitude;
    data['longitude'] = longitude;
    data['doc_date'] = docDate;
    if (detailPermintaan != null) {
      final v = detailPermintaan;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['detail_permintaan'] = arr0;
    }
    return data;
  }
}

class ApdRequestModel {
  /*
{
  "data": [
    {
      "id": "01jyjjy7bvmy2f9qes41ym4wcc",
      "created_at": "25/06/2025",
      "code": "033/REQ/K3L-MKP/VI/2025",
      "unit_name": "Kantor Pusat",
      "doc_status": "2",
      "description": "adaada",
      "longitude_latitude": "null",
      "doc_date": "25/06/2025 00:00",
      "detail_permintaan": [
        {
          "id": "01jyjjy7bzkv0hh2csc7fb3q5f",
          "apd_name": "SEPATU APD",
          "apd_id": "01jx6tpxkwghf6gp62sq27ng64",
          "qty_available": 2
        }
      ]
    }
  ],
  "message": "Data berhasil diambil",
  "status": true
} 
*/

  List<ApdRequestModelData?>? data;
  String? message;
  bool? status;

  ApdRequestModel({this.data, this.message, this.status});
  ApdRequestModel.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <ApdRequestModelData>[];
      v.forEach((v) {
        arr0.add(ApdRequestModelData.fromJson(v));
      });
      this.data = arr0;
    }
    message = json['message']?.toString();
    status = json['status'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}
