///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ApdRequestParamDataApd {
/*
{
  "id": "01jwbfjgzb6z87mwgnxvf3315p",
  "qty": 1
} 
*/

  String? id;
  String? code;
  String? name;
  int? qty;

  ApdRequestParamDataApd({
    this.id,
    this.code,
    this.name,
    this.qty,
  });
  ApdRequestParamDataApd.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    qty = json['qty']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['qty'] = qty;
    return data;
  }
}

class ApdRequestParam {
/*
{
  "doc_date": "2025-04-21 00:00:00",
  "description": "wiwok",
  "data_apd": [
    {
      "id": "01jwbfjgzb6z87mwgnxvf3315p",
      "qty": 1
    }
  ],
  "unit": "01jx5m230nsp9r160yb6n59g46",
  "action": "draft"
} 
*/

  String? docDate;
  String? description;
  List<ApdRequestParamDataApd?>? dataApd;
  String? unit;
  String? action;

  ApdRequestParam({
    this.docDate,
    this.description,
    this.dataApd,
    this.unit,
    this.action,
  });
  ApdRequestParam.fromJson(Map<String, dynamic> json) {
    docDate = json['doc_date']?.toString();
    description = json['description']?.toString();
  if (json['data_apd'] != null) {
  final v = json['data_apd'];
  final arr0 = <ApdRequestParamDataApd>[];
  v.forEach((v) {
  arr0.add(ApdRequestParamDataApd.fromJson(v));
  });
    dataApd = arr0;
    }
    unit = json['unit']?.toString();
    action = json['action']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['doc_date'] = docDate;
    data['description'] = description;
    if (dataApd != null) {
      final v = dataApd;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['data_apd'] = arr0;
    }
    data['unit'] = unit;
    data['action'] = action;
    return data;
  }
}
