import 'dart:convert';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ApdRequestParamDataApd {
  /*
{
  "id": "01jwbfjgzb6z87mwgnxvf3315p",
  "qty": 1
} 
*/

  String? id;
  String? apdId;
  String? apdName;
  int? qty;
  String? code;
  String? warna;
  String? ukuranBaju;
  String? ukuranCelana;
  String? ukuranSepatu;
  String? jenisSepatu;

  ApdRequestParamDataApd({
    this.id,
    this.apdId,
    this.apdName,
    this.qty,
    this.code,
    this.warna,
    this.ukuranBaju,
    this.ukuranCelana,
    this.ukuranSepatu,
    this.jenisSepatu,
  });
  ApdRequestParamDataApd.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    apdId = json['apd_id']?.toString();
    apdName = json['name']?.toString();
    qty = json['qty']?.toInt();
    code = json['code']?.toString();
    warna = json['warna']?.toString();
    ukuranBaju = json['ukuran_baju']?.toString();
    ukuranCelana = json['ukuran_celana']?.toString();
    ukuranSepatu = json['ukuran_sepatu']?.toString();
    jenisSepatu = json['jenis_sepatu']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    // data['apd_id'] = apdId;
    // data['name'] = apdName;
    data['qty'] = qty;
    // data['code'] = code;
    // data['warna'] = warna;
    // data['ukuran_baju'] = ukuranBaju;
    // data['ukuran_celana'] = ukuranCelana;
    // data['ukuran_sepatu'] = ukuranSepatu;
    // data['jenis_sepatu'] = jenisSepatu;
    return data;
  }
}

class ApdRequestParam {
  /*
{
  "doc_date": "2025-04-21 00:00:00",
  "description": "wiwok",
  "data_apd": [
    {
      "id": "01jwbfjgzb6z87mwgnxvf3315p",
      "qty": 1
    }
  ],
  "unit": "01jx5m230nsp9r160yb6n59g46",
  "action": "draft"
} 
*/

  String? id;
  String? docDate;
  String? description;
  List<ApdRequestParamDataApd?>? dataApd;
  String? unit;
  String? action;

  ApdRequestParam({
    this.id,
    this.docDate,
    this.description,
    this.dataApd,
    this.unit,
    this.action,
  });
  ApdRequestParam.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    docDate = json['doc_date']?.toString();
    description = json['description']?.toString();
    if (json['data_apd'] != null) {
      final v = json['data_apd'];
      final arr0 = <ApdRequestParamDataApd>[];
      v.forEach((v) {
        arr0.add(ApdRequestParamDataApd.fromJson(v));
      });
      dataApd = arr0;
    }
    unit = json['unit']?.toString();
    action = json['action']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (id != null) data['id'] = id;
    data['doc_date'] = docDate;
    data['description'] = description;
    if (dataApd != null) {
      final v = dataApd;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data_apd'] = jsonEncode(arr0);
    }
    data['unit'] = unit;
    if (action != null) data['action'] = action;
    return data;
  }
}
