///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ApdRequestViewModelDataLinimasa {
  /*
{
  "id": "01jxkq59t4qcgsxsm51t3cpwrg",
  "tanggal_action": "13/06/2025 04:00",
  "keterangan": "Permintaan APD diajukan",
  "user_name": "Admin K3"
} 
*/

  String? id;
  String? tanggalAction;
  String? keterangan;
  String? userName;

  ApdRequestViewModelDataLinimasa({
    this.id,
    this.tanggalAction,
    this.keterangan,
    this.userName,
  });
  ApdRequestViewModelDataLinimasa.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    tanggalAction = json['tanggal_action']?.toString();
    keterangan = json['keterangan']?.toString();
    userName = json['user_name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['tanggal_action'] = tanggalAction;
    data['keterangan'] = keterangan;
    data['user_name'] = userName;
    return data;
  }
}

class ApdRequestViewModelDataDaftarPermintaan {
  /*
{
  "id": "01jxkq59te4c298ff6ve7nr67x",
  "apd_id": "01jx6tpxkwghf6gp62sq27ng64",
  "apd_name": "SEPATU APD",
  "qty": 1,
  "code": "APD-000/WOM",
  "warna": "Merah",
  "ukuran_baju": "S",
  "ukuran_celana": "27",
  "ukuran_sepatu": "37",
  "jenis_sepatu": "Short"
} 
*/

  String? id;
  String? apdId;
  String? apdName;
  int? qty;
  String? code;
  String? warna;
  String? ukuranBaju;
  String? ukuranCelana;
  String? ukuranSepatu;
  String? jenisSepatu;

  ApdRequestViewModelDataDaftarPermintaan({
    this.id,
    this.apdId,
    this.apdName,
    this.qty,
    this.code,
    this.warna,
    this.ukuranBaju,
    this.ukuranCelana,
    this.ukuranSepatu,
    this.jenisSepatu,
  });
  ApdRequestViewModelDataDaftarPermintaan.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    apdId = json['apd_id']?.toString();
    apdName = json['apd_name']?.toString();
    qty = json['qty']?.toInt();
    code = json['code']?.toString();
    warna = json['warna']?.toString();
    ukuranBaju = json['ukuran_baju']?.toString();
    ukuranCelana = json['ukuran_celana']?.toString();
    ukuranSepatu = json['ukuran_sepatu']?.toString();
    jenisSepatu = json['jenis_sepatu']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['apd_id'] = apdId;
    data['apd_name'] = apdName;
    data['qty'] = qty;
    data['code'] = code;
    data['warna'] = warna;
    data['ukuran_baju'] = ukuranBaju;
    data['ukuran_celana'] = ukuranCelana;
    data['ukuran_sepatu'] = ukuranSepatu;
    data['jenis_sepatu'] = jenisSepatu;
    return data;
  }
}

class ApdRequestViewModelData {
  /*
{
  "id": "01jxkq59szn8m4vcz44xn4dj55",
  "created_at": "13/06/2025",
  "code": "019/REQ/K3L-MKP/VI/2025",
  "unit_name": "null",
  "doc_status": "0",
  "description": "aaad",
  "doc_date": "13/06/2025 00:00",
  "unit_id": "01jx5m230nsp9r160yb6n59g46",
  "daftar_permintaan": [
    {
      "id": "01jxkq59te4c298ff6ve7nr67x",
      "apd_id": "01jx6tpxkwghf6gp62sq27ng64",
      "apd_name": "SEPATU APD",
      "qty": 1,
      "code": "APD-000/WOM",
      "warna": "Merah",
      "ukuran_baju": "S",
      "ukuran_celana": "27",
      "ukuran_sepatu": "37",
      "jenis_sepatu": "Short"
    }
  ],
  "linimasa": [
    {
      "id": "01jxkq59t4qcgsxsm51t3cpwrg",
      "tanggal_action": "13/06/2025 04:00",
      "keterangan": "Permintaan APD diajukan",
      "user_name": "Admin K3"
    }
  ]
} 
*/

  String? id;
  String? createdAt;
  String? code;
  String? unitName;
  String? docStatus;
  String? description;
  String? docDate;
  String? unitId;
  List<ApdRequestViewModelDataDaftarPermintaan?>? daftarPermintaan;
  List<ApdRequestViewModelDataLinimasa?>? linimasa;

  ApdRequestViewModelData({
    this.id,
    this.createdAt,
    this.code,
    this.unitName,
    this.docStatus,
    this.description,
    this.docDate,
    this.unitId,
    this.daftarPermintaan,
    this.linimasa,
  });
  ApdRequestViewModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    createdAt = json['created_at']?.toString();
    code = json['code']?.toString();
    unitName = json['unit_name']?.toString();
    docStatus = json['doc_status']?.toString();
    description = json['description']?.toString();
    docDate = json['doc_date']?.toString();
    unitId = json['unit_id']?.toString();
    if (json['daftar_permintaan'] != null) {
      final v = json['daftar_permintaan'];
      final arr0 = <ApdRequestViewModelDataDaftarPermintaan>[];
      v.forEach((v) {
        arr0.add(ApdRequestViewModelDataDaftarPermintaan.fromJson(v));
      });
      daftarPermintaan = arr0;
    }
    if (json['linimasa'] != null) {
      final v = json['linimasa'];
      final arr0 = <ApdRequestViewModelDataLinimasa>[];
      v.forEach((v) {
        arr0.add(ApdRequestViewModelDataLinimasa.fromJson(v));
      });
      linimasa = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['created_at'] = createdAt;
    data['code'] = code;
    data['unit_name'] = unitName;
    data['doc_status'] = docStatus;
    data['description'] = description;
    data['doc_date'] = docDate;
    data['unit_id'] = unitId;
    if (daftarPermintaan != null) {
      final v = daftarPermintaan;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['daftar_permintaan'] = arr0;
    }
    if (linimasa != null) {
      final v = linimasa;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['linimasa'] = arr0;
    }
    return data;
  }
}

class ApdRequestViewModel {
  /*
{
  "data": {
    "id": "01jxkq59szn8m4vcz44xn4dj55",
    "created_at": "13/06/2025",
    "code": "019/REQ/K3L-MKP/VI/2025",
    "unit_name": "null",
    "doc_status": "0",
    "description": "aaad",
    "doc_date": "13/06/2025 00:00",
    "unit_id": "01jx5m230nsp9r160yb6n59g46",
    "daftar_permintaan": [
      {
        "id": "01jxkq59te4c298ff6ve7nr67x",
        "apd_id": "01jx6tpxkwghf6gp62sq27ng64",
        "apd_name": "SEPATU APD",
        "qty": 1,
        "code": "APD-000/WOM",
        "warna": "Merah",
        "ukuran_baju": "S",
        "ukuran_celana": "27",
        "ukuran_sepatu": "37",
        "jenis_sepatu": "Short"
      }
    ],
    "linimasa": [
      {
        "id": "01jxkq59t4qcgsxsm51t3cpwrg",
        "tanggal_action": "13/06/2025 04:00",
        "keterangan": "Permintaan APD diajukan",
        "user_name": "Admin K3"
      }
    ]
  },
  "message": "Data berhasil diambil",
  "status": true
} 
*/

  ApdRequestViewModelData? data;
  String? message;
  bool? status;

  ApdRequestViewModel({this.data, this.message, this.status});
  ApdRequestViewModel.fromJson(Map<String, dynamic> json) {
    data =
        (json['data'] != null)
            ? ApdRequestViewModelData.fromJson(json['data'])
            : null;
    message = json['message']?.toString();
    status = json['status'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}
