///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ApdRequestModelData {
/*
{
  "id": "01jx74qh74045zrkdm0ccch8p0",
  "created_at": "08/06/2025",
  "code": "001/REQ/K3L-MKP/VI/2025",
  "unit_name": "Kantor Pusat",
  "doc_status": "0",
  "description": "wuwuwu",
  "doc_date": "03/06/2025 00:00"
} 
*/

  String? id;
  String? createdAt;
  String? code;
  String? unitName;
  String? docStatus;
  String? description;
  String? docDate;

  ApdRequestModelData({
    this.id,
    this.createdAt,
    this.code,
    this.unitName,
    this.docStatus,
    this.description,
    this.docDate,
  });
  ApdRequestModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    createdAt = json['created_at']?.toString();
    code = json['code']?.toString();
    unitName = json['unit_name']?.toString();
    docStatus = json['doc_status']?.toString();
    description = json['description']?.toString();
    docDate = json['doc_date']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['created_at'] = createdAt;
    data['code'] = code;
    data['unit_name'] = unitName;
    data['doc_status'] = docStatus;
    data['description'] = description;
    data['doc_date'] = docDate;
    return data;
  }
}

class ApdRequestModel {
/*
{
  "data": [
    {
      "id": "01jx74qh74045zrkdm0ccch8p0",
      "created_at": "08/06/2025",
      "code": "001/REQ/K3L-MKP/VI/2025",
      "unit_name": "Kantor Pusat",
      "doc_status": "0",
      "description": "wuwuwu",
      "doc_date": "03/06/2025 00:00"
    }
  ],
  "message": "Data berhasil diambil",
  "status": true
} 
*/

  List<ApdRequestModelData?>? data;
  String? message;
  bool? status;

  ApdRequestModel({
    this.data,
    this.message,
    this.status,
  });
  ApdRequestModel.fromJson(Map<String, dynamic> json) {
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <ApdRequestModelData>[];
  v.forEach((v) {
  arr0.add(ApdRequestModelData.fromJson(v));
  });
    this.data = arr0;
    }
    message = json['message']?.toString();
    status = json['status'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['data'] = arr0;
    }
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}
