///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ApdRequestViewModelDataDaftarPermintaan {
/*
{
  "id": "01jx74qhbp132d216bw8f4j230",
  "apd_id": "01jx6tpxkwghf6gp62sq27ng64",
  "apd_name": "SEPATU APD",
  "qty": 10
} 
*/

  String? id;
  String? apdId;
  String? apdName;
  int? qty;

  ApdRequestViewModelDataDaftarPermintaan({
    this.id,
    this.apdId,
    this.apdName,
    this.qty,
  });
  ApdRequestViewModelDataDaftarPermintaan.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    apdId = json['apd_id']?.toString();
    apdName = json['apd_name']?.toString();
    qty = json['qty']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['apd_id'] = apdId;
    data['apd_name'] = apdName;
    data['qty'] = qty;
    return data;
  }
}

class ApdRequestViewModelData {
/*
{
  "id": "01jx74qh74045zrkdm0ccch8p0",
  "created_at": "08/06/2025",
  "code": "001/REQ/K3L-MKP/VI/2025",
  "unit_name": "null",
  "doc_status": "0",
  "description": "wuwuwu",
  "doc_date": "03/06/2025 00:00",
  "unit_id": "01jx5m230nsp9r160yb6n59g46",
  "daftar_permintaan": [
    {
      "id": "01jx74qhbp132d216bw8f4j230",
      "apd_id": "01jx6tpxkwghf6gp62sq27ng64",
      "apd_name": "SEPATU APD",
      "qty": 10
    }
  ]
} 
*/

  String? id;
  String? createdAt;
  String? code;
  String? unitName;
  String? docStatus;
  String? description;
  String? docDate;
  String? unitId;
  List<ApdRequestViewModelDataDaftarPermintaan?>? daftarPermintaan;

  ApdRequestViewModelData({
    this.id,
    this.createdAt,
    this.code,
    this.unitName,
    this.docStatus,
    this.description,
    this.docDate,
    this.unitId,
    this.daftarPermintaan,
  });
  ApdRequestViewModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    createdAt = json['created_at']?.toString();
    code = json['code']?.toString();
    unitName = json['unit_name']?.toString();
    docStatus = json['doc_status']?.toString();
    description = json['description']?.toString();
    docDate = json['doc_date']?.toString();
    unitId = json['unit_id']?.toString();
  if (json['daftar_permintaan'] != null) {
  final v = json['daftar_permintaan'];
  final arr0 = <ApdRequestViewModelDataDaftarPermintaan>[];
  v.forEach((v) {
  arr0.add(ApdRequestViewModelDataDaftarPermintaan.fromJson(v));
  });
    daftarPermintaan = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['created_at'] = createdAt;
    data['code'] = code;
    data['unit_name'] = unitName;
    data['doc_status'] = docStatus;
    data['description'] = description;
    data['doc_date'] = docDate;
    data['unit_id'] = unitId;
    if (daftarPermintaan != null) {
      final v = daftarPermintaan;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['daftar_permintaan'] = arr0;
    }
    return data;
  }
}

class ApdRequestViewModel {
/*
{
  "data": {
    "id": "01jx74qh74045zrkdm0ccch8p0",
    "created_at": "08/06/2025",
    "code": "001/REQ/K3L-MKP/VI/2025",
    "unit_name": "null",
    "doc_status": "0",
    "description": "wuwuwu",
    "doc_date": "03/06/2025 00:00",
    "unit_id": "01jx5m230nsp9r160yb6n59g46",
    "daftar_permintaan": [
      {
        "id": "01jx74qhbp132d216bw8f4j230",
        "apd_id": "01jx6tpxkwghf6gp62sq27ng64",
        "apd_name": "SEPATU APD",
        "qty": 10
      }
    ]
  },
  "message": "Data berhasil diambil",
  "status": true
} 
*/

  ApdRequestViewModelData? data;
  String? message;
  bool? status;

  ApdRequestViewModel({
    this.data,
    this.message,
    this.status,
  });
  ApdRequestViewModel.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null) ? ApdRequestViewModelData.fromJson(json['data']) : null;
    message = json['message']?.toString();
    status = json['status'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}
