///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginModelDataKaryawanUnit {
  /*
{
  "id": "01jx5m230nsp9r160yb6n59g46",
  "name": "Kantor Pusat",
  "code": "U0001"
} 
*/

  String? id;
  String? name;
  String? code;

  LoginModelDataKaryawanUnit({this.id, this.name, this.code});
  LoginModelDataKaryawanUnit.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    code = json['code']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['code'] = code;
    return data;
  }
}

class LoginModelDataKaryawan {
  /*
{
  "id": "01jx5m236advexa306q0cyhqee",
  "nid": "1234567890",
  "name": "Admin K3",
  "md_tipe_akun_id": "01jx5m22aqtkwkaw6eh9zma43f",
  "md_unit_id": "01jx5m230nsp9r160yb6n59g46",
  "md_instansi_id": "null",
  "jabatan": "null",
  "created_at": "2025-06-07T16:37:23.000000Z",
  "updated_at": "2025-06-07T16:37:23.000000Z",
  "deleted_at": "null",
  "unit": {
    "id": "01jx5m230nsp9r160yb6n59g46",
    "name": "Kantor Pusat",
    "code": "U0001"
  }
} 
*/

  String? id;
  String? nid;
  String? name;
  String? mdTipeAkunId;
  String? mdUnitId;
  String? mdInstansiId;
  String? jabatan;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;
  LoginModelDataKaryawanUnit? unit;

  LoginModelDataKaryawan({
    this.id,
    this.nid,
    this.name,
    this.mdTipeAkunId,
    this.mdUnitId,
    this.mdInstansiId,
    this.jabatan,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.unit,
  });
  LoginModelDataKaryawan.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    nid = json['nid']?.toString();
    name = json['name']?.toString();
    mdTipeAkunId = json['md_tipe_akun_id']?.toString();
    mdUnitId = json['md_unit_id']?.toString();
    mdInstansiId = json['md_instansi_id']?.toString();
    jabatan = json['jabatan']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    deletedAt = json['deleted_at']?.toString();
    unit =
        (json['unit'] != null)
            ? LoginModelDataKaryawanUnit.fromJson(json['unit'])
            : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['nid'] = nid;
    data['name'] = name;
    data['md_tipe_akun_id'] = mdTipeAkunId;
    data['md_unit_id'] = mdUnitId;
    data['md_instansi_id'] = mdInstansiId;
    data['jabatan'] = jabatan;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['deleted_at'] = deletedAt;
    if (unit != null) {
      data['unit'] = unit!.toJson();
    }
    return data;
  }
}

class LoginModelData {
  /*
{
  "id": "01jx5m23g7gca309z0aq7ka4zc",
  "name": "Admin K3",
  "nid": "1234567890",
  "md_karyawan_id": "01jx5m236advexa306q0cyhqee",
  "md_role_id": "01jx5m2348sps98z7504wawp9g",
  "email_verified_at": "null",
  "is_active": 1,
  "created_at": "2025-06-07T16:37:24.000000Z",
  "updated_at": "2025-06-07T16:37:24.000000Z",
  "deleted_at": "null",
  "unit_name": "Kantor Pusat",
  "unit_id": "01jx5m230nsp9r160yb6n59g46",
  "karyawan": {
    "id": "01jx5m236advexa306q0cyhqee",
    "nid": "1234567890",
    "name": "Admin K3",
    "md_tipe_akun_id": "01jx5m22aqtkwkaw6eh9zma43f",
    "md_unit_id": "01jx5m230nsp9r160yb6n59g46",
    "md_instansi_id": "null",
    "jabatan": "null",
    "created_at": "2025-06-07T16:37:23.000000Z",
    "updated_at": "2025-06-07T16:37:23.000000Z",
    "deleted_at": "null",
    "unit": {
      "id": "01jx5m230nsp9r160yb6n59g46",
      "name": "Kantor Pusat",
      "code": "U0001"
    }
  }
} 
*/

  String? id;
  String? name;
  String? nid;
  String? mdKaryawanId;
  String? mdRoleId;
  String? emailVerifiedAt;
  int? isActive;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;
  String? unitName;
  String? unitId;
  LoginModelDataKaryawan? karyawan;

  LoginModelData({
    this.id,
    this.name,
    this.nid,
    this.mdKaryawanId,
    this.mdRoleId,
    this.emailVerifiedAt,
    this.isActive,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.unitName,
    this.unitId,
    this.karyawan,
  });
  LoginModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    nid = json['nid']?.toString();
    mdKaryawanId = json['md_karyawan_id']?.toString();
    mdRoleId = json['md_role_id']?.toString();
    emailVerifiedAt = json['email_verified_at']?.toString();
    isActive = json['is_active']?.toInt();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    deletedAt = json['deleted_at']?.toString();
    unitName = json['unit_name']?.toString();
    unitId = json['unit_id']?.toString();
    karyawan =
        (json['karyawan'] != null)
            ? LoginModelDataKaryawan.fromJson(json['karyawan'])
            : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['nid'] = nid;
    data['md_karyawan_id'] = mdKaryawanId;
    data['md_role_id'] = mdRoleId;
    data['email_verified_at'] = emailVerifiedAt;
    data['is_active'] = isActive;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['deleted_at'] = deletedAt;
    data['unit_name'] = unitName;
    data['unit_id'] = unitId;
    if (karyawan != null) {
      data['karyawan'] = karyawan!.toJson();
    }
    return data;
  }
}

class LoginModel {
  /*
{
  "data": {
    "id": "01jx5m23g7gca309z0aq7ka4zc",
    "name": "Admin K3",
    "nid": "1234567890",
    "md_karyawan_id": "01jx5m236advexa306q0cyhqee",
    "md_role_id": "01jx5m2348sps98z7504wawp9g",
    "email_verified_at": "null",
    "is_active": 1,
    "created_at": "2025-06-07T16:37:24.000000Z",
    "updated_at": "2025-06-07T16:37:24.000000Z",
    "deleted_at": "null",
    "unit_name": "Kantor Pusat",
    "unit_id": "01jx5m230nsp9r160yb6n59g46",
    "karyawan": {
      "id": "01jx5m236advexa306q0cyhqee",
      "nid": "1234567890",
      "name": "Admin K3",
      "md_tipe_akun_id": "01jx5m22aqtkwkaw6eh9zma43f",
      "md_unit_id": "01jx5m230nsp9r160yb6n59g46",
      "md_instansi_id": "null",
      "jabatan": "null",
      "created_at": "2025-06-07T16:37:23.000000Z",
      "updated_at": "2025-06-07T16:37:23.000000Z",
      "deleted_at": "null",
      "unit": {
        "id": "01jx5m230nsp9r160yb6n59g46",
        "name": "Kantor Pusat",
        "code": "U0001"
      }
    }
  },
  "token": "3|oRbVIH6jGiI8Cfo4cQwYdaI0RghxxpQhtDFTqf3k0843d925",
  "message": "Ok",
  "status": true
} 
*/

  LoginModelData? data;
  String? token;
  String? message;
  bool? status;

  LoginModel({this.data, this.token, this.message, this.status});
  LoginModel.fromJson(Map<String, dynamic> json) {
    data =
        (json['data'] != null) ? LoginModelData.fromJson(json['data']) : null;
    token = json['token']?.toString();
    message = json['message']?.toString();
    status = json['status'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['token'] = token;
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}
