///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginModelData {
  /*
{
  "id": "01jt56e21qxc34mvktcayhyv0x",
  "created_at": "01/05/2025",
  "code": "000/F.INS-NM/K3L-MKP/X/2025",
  "type": "1",
  "kategori_name": "Near Miss",
  "doc_status": "1",
  "lokasi": "serlokk",
  "petugas": "Ichul",
  "doc_date": "04/10/2025 21:00"
} 
*/

  String? id;
  String? createdAt;
  String? code;
  String? type;
  String? kategoriName;
  String? docStatus;
  String? lokasi;
  String? petugas;
  String? docDate;

  LoginModelData({
    this.id,
    this.createdAt,
    this.code,
    this.type,
    this.kategoriName,
    this.docStatus,
    this.lokasi,
    this.petugas,
    this.docDate,
  });
  LoginModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    createdAt = json['created_at']?.toString();
    code = json['code']?.toString();
    type = json['type']?.toString();
    kategoriName = json['kategori_name']?.toString();
    docStatus = json['doc_status']?.toString();
    lokasi = json['lokasi']?.toString();
    petugas = json['petugas']?.toString();
    docDate = json['doc_date']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['created_at'] = createdAt;
    data['code'] = code;
    data['type'] = type;
    data['kategori_name'] = kategoriName;
    data['doc_status'] = docStatus;
    data['lokasi'] = lokasi;
    data['petugas'] = petugas;
    data['doc_date'] = docDate;
    return data;
  }
}

class LoginModel {
  /*
{
  "data": [
    {
      "id": "01jt56e21qxc34mvktcayhyv0x",
      "created_at": "01/05/2025",
      "code": "000/F.INS-NM/K3L-MKP/X/2025",
      "type": "1",
      "kategori_name": "Near Miss",
      "doc_status": "1",
      "lokasi": "serlokk",
      "petugas": "Ichul",
      "doc_date": "04/10/2025 21:00"
    }
  ],
  "message": "Data berhasil diambil",
  "status": true
} 
*/

  List<LoginModelData?>? data;
  String? message;
  bool? status;

  LoginModel({this.data, this.message, this.status});
  LoginModel.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <LoginModelData>[];
      v.forEach((v) {
        arr0.add(LoginModelData.fromJson(v));
      });
      this.data = arr0;
    }
    message = json['message']?.toString();
    status = json['status'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}
