///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginModelDataRole {
/*
{
  "id": "01jx9q3h2s7y3hq7p3mxkqc8ey",
  "name": "Super Admin",
  "code": "SADM"
} 
*/

  String? id;
  String? name;
  String? code;

  LoginModelDataRole({
    this.id,
    this.name,
    this.code,
  });
  LoginModelDataRole.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    code = json['code']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['code'] = code;
    return data;
  }
}

class LoginModelDataKaryawanTipeAkun {
/*
{
  "id": "01jx9q2y3nq6a7k7dnzzp6m8rr",
  "name": "MKP",
  "code": "MKP"
} 
*/

  String? id;
  String? name;
  String? code;

  LoginModelDataKaryawanTipeAkun({
    this.id,
    this.name,
    this.code,
  });
  LoginModelDataKaryawanTipeAkun.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    code = json['code']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['code'] = code;
    return data;
  }
}

class LoginModelDataKaryawanUnit {
/*
{
  "id": "01jx9q3fc4a5rqhpd4q97s413p",
  "name": "Kantor Pusat",
  "code": "U0001"
} 
*/

  String? id;
  String? name;
  String? code;

  LoginModelDataKaryawanUnit({
    this.id,
    this.name,
    this.code,
  });
  LoginModelDataKaryawanUnit.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    code = json['code']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['code'] = code;
    return data;
  }
}

class LoginModelDataKaryawan {
/*
{
  "id": "01jx9q3j86ara3bpwsnpex11qs",
  "nid": "1234567890",
  "name": "Admin K3",
  "md_tipe_akun_id": "01jx9q2y3nq6a7k7dnzzp6m8rr",
  "md_unit_id": "01jx9q3fc4a5rqhpd4q97s413p",
  "md_instansi_id": "null",
  "jabatan": "Administrator",
  "created_at": "2025-06-08T23:47:35.000000Z",
  "updated_at": "2025-06-09T15:22:17.000000Z",
  "deleted_at": "null",
  "unit": {
    "id": "01jx9q3fc4a5rqhpd4q97s413p",
    "name": "Kantor Pusat",
    "code": "U0001"
  },
  "instansi": "null",
  "tipe_akun": {
    "id": "01jx9q2y3nq6a7k7dnzzp6m8rr",
    "name": "MKP",
    "code": "MKP"
  }
} 
*/

  String? id;
  String? nid;
  String? name;
  String? mdTipeAkunId;
  String? mdUnitId;
  String? mdInstansiId;
  String? jabatan;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;
  LoginModelDataKaryawanUnit? unit;
  String? instansi;
  LoginModelDataKaryawanTipeAkun? tipeAkun;

  LoginModelDataKaryawan({
    this.id,
    this.nid,
    this.name,
    this.mdTipeAkunId,
    this.mdUnitId,
    this.mdInstansiId,
    this.jabatan,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.unit,
    this.instansi,
    this.tipeAkun,
  });
  LoginModelDataKaryawan.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    nid = json['nid']?.toString();
    name = json['name']?.toString();
    mdTipeAkunId = json['md_tipe_akun_id']?.toString();
    mdUnitId = json['md_unit_id']?.toString();
    mdInstansiId = json['md_instansi_id']?.toString();
    jabatan = json['jabatan']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    deletedAt = json['deleted_at']?.toString();
    unit = (json['unit'] != null) ? LoginModelDataKaryawanUnit.fromJson(json['unit']) : null;
    instansi = json['instansi']?.toString();
    tipeAkun = (json['tipe_akun'] != null) ? LoginModelDataKaryawanTipeAkun.fromJson(json['tipe_akun']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['nid'] = nid;
    data['name'] = name;
    data['md_tipe_akun_id'] = mdTipeAkunId;
    data['md_unit_id'] = mdUnitId;
    data['md_instansi_id'] = mdInstansiId;
    data['jabatan'] = jabatan;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['deleted_at'] = deletedAt;
    if (unit != null) {
      data['unit'] = unit!.toJson();
    }
    data['instansi'] = instansi;
    if (tipeAkun != null) {
      data['tipe_akun'] = tipeAkun!.toJson();
    }
    return data;
  }
}

class LoginModelData {
/*
{
  "id": "01jx9q3ws69mmy8ttwdekbbecx",
  "name": "Admin K3",
  "nid": "1234567890",
  "md_karyawan_id": "01jx9q3j86ara3bpwsnpex11qs",
  "md_role_id": "01jx9q3h2s7y3hq7p3mxkqc8ey",
  "email_verified_at": "null",
  "is_active": 1,
  "created_at": "2025-06-08T23:47:46.000000Z",
  "updated_at": "2025-06-11T04:48:26.000000Z",
  "deleted_at": "null",
  "unit_name": "Kantor Pusat",
  "unit_id": "01jx9q3fc4a5rqhpd4q97s413p",
  "instansi_id": "-",
  "instansi_name": "-",
  "tipe_akun_id": "01jx9q2y3nq6a7k7dnzzp6m8rr",
  "tipe_akun_name": "MKP",
  "role_id": "01jx9q3h2s7y3hq7p3mxkqc8ey",
  "role_name": "Super Admin",
  "role_code": "SADM",
  "karyawan": {
    "id": "01jx9q3j86ara3bpwsnpex11qs",
    "nid": "1234567890",
    "name": "Admin K3",
    "md_tipe_akun_id": "01jx9q2y3nq6a7k7dnzzp6m8rr",
    "md_unit_id": "01jx9q3fc4a5rqhpd4q97s413p",
    "md_instansi_id": "null",
    "jabatan": "Administrator",
    "created_at": "2025-06-08T23:47:35.000000Z",
    "updated_at": "2025-06-09T15:22:17.000000Z",
    "deleted_at": "null",
    "unit": {
      "id": "01jx9q3fc4a5rqhpd4q97s413p",
      "name": "Kantor Pusat",
      "code": "U0001"
    },
    "instansi": "null",
    "tipe_akun": {
      "id": "01jx9q2y3nq6a7k7dnzzp6m8rr",
      "name": "MKP",
      "code": "MKP"
    }
  },
  "role": {
    "id": "01jx9q3h2s7y3hq7p3mxkqc8ey",
    "name": "Super Admin",
    "code": "SADM"
  }
} 
*/

  String? id;
  String? name;
  String? nid;
  String? mdKaryawanId;
  String? mdRoleId;
  String? emailVerifiedAt;
  int? isActive;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;
  String? unitName;
  String? unitId;
  String? instansiId;
  String? instansiName;
  String? tipeAkunId;
  String? tipeAkunName;
  String? roleId;
  String? roleName;
  String? roleCode;
  LoginModelDataKaryawan? karyawan;
  LoginModelDataRole? role;

  LoginModelData({
    this.id,
    this.name,
    this.nid,
    this.mdKaryawanId,
    this.mdRoleId,
    this.emailVerifiedAt,
    this.isActive,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.unitName,
    this.unitId,
    this.instansiId,
    this.instansiName,
    this.tipeAkunId,
    this.tipeAkunName,
    this.roleId,
    this.roleName,
    this.roleCode,
    this.karyawan,
    this.role,
  });
  LoginModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    nid = json['nid']?.toString();
    mdKaryawanId = json['md_karyawan_id']?.toString();
    mdRoleId = json['md_role_id']?.toString();
    emailVerifiedAt = json['email_verified_at']?.toString();
    isActive = json['is_active']?.toInt();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    deletedAt = json['deleted_at']?.toString();
    unitName = json['unit_name']?.toString();
    unitId = json['unit_id']?.toString();
    instansiId = json['instansi_id']?.toString();
    instansiName = json['instansi_name']?.toString();
    tipeAkunId = json['tipe_akun_id']?.toString();
    tipeAkunName = json['tipe_akun_name']?.toString();
    roleId = json['role_id']?.toString();
    roleName = json['role_name']?.toString();
    roleCode = json['role_code']?.toString();
    karyawan = (json['karyawan'] != null) ? LoginModelDataKaryawan.fromJson(json['karyawan']) : null;
    role = (json['role'] != null) ? LoginModelDataRole.fromJson(json['role']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['nid'] = nid;
    data['md_karyawan_id'] = mdKaryawanId;
    data['md_role_id'] = mdRoleId;
    data['email_verified_at'] = emailVerifiedAt;
    data['is_active'] = isActive;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['deleted_at'] = deletedAt;
    data['unit_name'] = unitName;
    data['unit_id'] = unitId;
    data['instansi_id'] = instansiId;
    data['instansi_name'] = instansiName;
    data['tipe_akun_id'] = tipeAkunId;
    data['tipe_akun_name'] = tipeAkunName;
    data['role_id'] = roleId;
    data['role_name'] = roleName;
    data['role_code'] = roleCode;
    if (karyawan != null) {
      data['karyawan'] = karyawan!.toJson();
    }
    if (role != null) {
      data['role'] = role!.toJson();
    }
    return data;
  }
}

class LoginModel {
/*
{
  "data": {
    "id": "01jx9q3ws69mmy8ttwdekbbecx",
    "name": "Admin K3",
    "nid": "1234567890",
    "md_karyawan_id": "01jx9q3j86ara3bpwsnpex11qs",
    "md_role_id": "01jx9q3h2s7y3hq7p3mxkqc8ey",
    "email_verified_at": "null",
    "is_active": 1,
    "created_at": "2025-06-08T23:47:46.000000Z",
    "updated_at": "2025-06-11T04:48:26.000000Z",
    "deleted_at": "null",
    "unit_name": "Kantor Pusat",
    "unit_id": "01jx9q3fc4a5rqhpd4q97s413p",
    "instansi_id": "-",
    "instansi_name": "-",
    "tipe_akun_id": "01jx9q2y3nq6a7k7dnzzp6m8rr",
    "tipe_akun_name": "MKP",
    "role_id": "01jx9q3h2s7y3hq7p3mxkqc8ey",
    "role_name": "Super Admin",
    "role_code": "SADM",
    "karyawan": {
      "id": "01jx9q3j86ara3bpwsnpex11qs",
      "nid": "1234567890",
      "name": "Admin K3",
      "md_tipe_akun_id": "01jx9q2y3nq6a7k7dnzzp6m8rr",
      "md_unit_id": "01jx9q3fc4a5rqhpd4q97s413p",
      "md_instansi_id": "null",
      "jabatan": "Administrator",
      "created_at": "2025-06-08T23:47:35.000000Z",
      "updated_at": "2025-06-09T15:22:17.000000Z",
      "deleted_at": "null",
      "unit": {
        "id": "01jx9q3fc4a5rqhpd4q97s413p",
        "name": "Kantor Pusat",
        "code": "U0001"
      },
      "instansi": "null",
      "tipe_akun": {
        "id": "01jx9q2y3nq6a7k7dnzzp6m8rr",
        "name": "MKP",
        "code": "MKP"
      }
    },
    "role": {
      "id": "01jx9q3h2s7y3hq7p3mxkqc8ey",
      "name": "Super Admin",
      "code": "SADM"
    }
  },
  "token": "16|xaqs5GU8kZnyOC4RU8brBUyPV8hGsoWR9x5bEKbLe9ebad5b",
  "message": "Ok",
  "status": true
} 
*/

  LoginModelData? data;
  String? token;
  String? message;
  bool? status;

  LoginModel({
    this.data,
    this.token,
    this.message,
    this.status,
  });
  LoginModel.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null) ? LoginModelData.fromJson(json['data']) : null;
    token = json['token']?.toString();
    message = json['message']?.toString();
    status = json['status'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['data'] = this.data!.toJson();
      data['token'] = token;
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}
