///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AddressModelAddress {
/*
{
  "road": "Jalan Ki Nameng",
  "city": "Lamongan",
  "county": "Lamongan",
  "state": "East Java",
  "region": "Java",
  "postcode": "62211",
  "country": "Indonesia",
  "country_code": "id"
} 
*/

  String? road;
  String? city;
  String? county;
  String? state;
  String? region;
  String? postcode;
  String? country;
  String? countryCode;

  AddressModelAddress({
    this.road,
    this.city,
    this.county,
    this.state,
    this.region,
    this.postcode,
    this.country,
    this.countryCode,
  });
  AddressModelAddress.fromJson(Map<String, dynamic> json) {
    road = json['road']?.toString();
    city = json['city']?.toString();
    county = json['county']?.toString();
    state = json['state']?.toString();
    region = json['region']?.toString();
    postcode = json['postcode']?.toString();
    country = json['country']?.toString();
    countryCode = json['country_code']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['road'] = road;
    data['city'] = city;
    data['county'] = county;
    data['state'] = state;
    data['region'] = region;
    data['postcode'] = postcode;
    data['country'] = country;
    data['country_code'] = countryCode;
    return data;
  }
}

class AddressModel {
/*
{
  "place_id": 24873861,
  "osm_id": 255991212,
  "lat": "-7.114341917613677",
  "lon": "112.41730224855782",
  "category": "highway",
  "type": "unclassified",
  "place_rank": 26,
  "importance": 0.05337833447775994,
  "addresstype": "road",
  "name": "Jalan Ki Nameng",
  "display_name": "Jalan Ki Nameng, Lamongan, East Java, Java, 62211, Indonesia",
  "address": {
    "road": "Jalan Ki Nameng",
    "city": "Lamongan",
    "county": "Lamongan",
    "state": "East Java",
    "region": "Java",
    "postcode": "62211",
    "country": "Indonesia",
    "country_code": "id"
  },
  "boundingbox": [
    "-7.1182890"
  ]
} 
*/

  int? placeId;
  int? osmId;
  String? lat;
  String? lon;
  String? category;
  String? type;
  int? placeRank;
  double? importance;
  String? addresstype;
  String? name;
  String? displayName;
  AddressModelAddress? address;
  List<String?>? boundingbox;

  AddressModel({
    this.placeId,
    this.osmId,
    this.lat,
    this.lon,
    this.category,
    this.type,
    this.placeRank,
    this.importance,
    this.addresstype,
    this.name,
    this.displayName,
    this.address,
    this.boundingbox,
  });
  AddressModel.fromJson(Map<String, dynamic> json) {
    placeId = json['place_id']?.toInt();
    osmId = json['osm_id']?.toInt();
    lat = json['lat']?.toString();
    lon = json['lon']?.toString();
    category = json['category']?.toString();
    type = json['type']?.toString();
    placeRank = json['place_rank']?.toInt();
    importance = json['importance']?.toDouble();
    addresstype = json['addresstype']?.toString();
    name = json['name']?.toString();
    displayName = json['display_name']?.toString();
    address = (json['address'] != null) ? AddressModelAddress.fromJson(json['address']) : null;
  if (json['boundingbox'] != null) {
  final v = json['boundingbox'];
  final arr0 = <String>[];
  v.forEach((v) {
  arr0.add(v.toString());
  });
    boundingbox = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['place_id'] = placeId;
    data['osm_id'] = osmId;
    data['lat'] = lat;
    data['lon'] = lon;
    data['category'] = category;
    data['type'] = type;
    data['place_rank'] = placeRank;
    data['importance'] = importance;
    data['addresstype'] = addresstype;
    data['name'] = name;
    data['display_name'] = displayName;
    if (address != null) {
      data['address'] = address!.toJson();
    }
    if (boundingbox != null) {
      final v = boundingbox;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v);
  });
      data['boundingbox'] = arr0;
    }
    return data;
  }
}
