///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ApdReceptionModelData {
/*
{
  "id": "01jy0g6rcrfcnqr9c0rtybfvj1",
  "penerimaa_code": "015/DLR/K3L-MKP/VI/2025",
  "doc_date": "18/06/2025",
  "pengeluaran_code": "abc",
  "request_code": "032/REQ/K3L-MKP/VI/2025",
  "request_date": "16/06/2025",
  "keterangan": "",
  "unit": "Kantor Pusat",
  "status": "Draft"
} 
*/

  String? id;
  String? penerimaaCode;
  String? docDate;
  String? pengeluaranCode;
  String? requestCode;
  String? requestDate;
  String? keterangan;
  String? unit;
  String? status;

  ApdReceptionModelData({
    this.id,
    this.penerimaaCode,
    this.docDate,
    this.pengeluaranCode,
    this.requestCode,
    this.requestDate,
    this.keterangan,
    this.unit,
    this.status,
  });
  ApdReceptionModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    penerimaaCode = json['penerimaa_code']?.toString();
    docDate = json['doc_date']?.toString();
    pengeluaranCode = json['pengeluaran_code']?.toString();
    requestCode = json['request_code']?.toString();
    requestDate = json['request_date']?.toString();
    keterangan = json['keterangan']?.toString();
    unit = json['unit']?.toString();
    status = json['status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['penerimaa_code'] = penerimaaCode;
    data['doc_date'] = docDate;
    data['pengeluaran_code'] = pengeluaranCode;
    data['request_code'] = requestCode;
    data['request_date'] = requestDate;
    data['keterangan'] = keterangan;
    data['unit'] = unit;
    data['status'] = status;
    return data;
  }
}

class ApdReceptionModel {
/*
{
  "data": [
    {
      "id": "01jy0g6rcrfcnqr9c0rtybfvj1",
      "penerimaa_code": "015/DLR/K3L-MKP/VI/2025",
      "doc_date": "18/06/2025",
      "pengeluaran_code": "abc",
      "request_code": "032/REQ/K3L-MKP/VI/2025",
      "request_date": "16/06/2025",
      "keterangan": "",
      "unit": "Kantor Pusat",
      "status": "Draft"
    }
  ],
  "message": "Data berhasil diambil",
  "status": true
} 
*/

  List<ApdReceptionModelData?>? data;
  String? message;
  bool? status;

  ApdReceptionModel({
    this.data,
    this.message,
    this.status,
  });
  ApdReceptionModel.fromJson(Map<String, dynamic> json) {
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <ApdReceptionModelData>[];
  v.forEach((v) {
  arr0.add(ApdReceptionModelData.fromJson(v));
  });
    this.data = arr0;
    }
    message = json['message']?.toString();
    status = json['status'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['data'] = arr0;
    }
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}
