///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ApdReceptionViewModelDataDaftarPenerimaan {
/*
{
  "id": "01jxa05ka0anj115rkhsjthw0q",
  "apd_id": "01jx6tpxkwghf6gp62sq27ng64",
  "apd_name": "SEPATU APD",
  "qty": 1
} 
*/

  String? id;
  String? apdId;
  String? apdName;
  int? qty;

  ApdReceptionViewModelDataDaftarPenerimaan({
    this.id,
    this.apdId,
    this.apdName,
    this.qty,
  });
  ApdReceptionViewModelDataDaftarPenerimaan.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    apdId = json['apd_id']?.toString();
    apdName = json['apd_name']?.toString();
    qty = json['qty']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['apd_id'] = apdId;
    data['apd_name'] = apdName;
    data['qty'] = qty;
    return data;
  }
}

class ApdReceptionViewModelData {
/*
{
  "id": "01jxa05k9xhea0sheaseza9vd9",
  "created_at": "09/06/2025",
  "permintaan_code": "000/REQ/K3L-MKP/VI/2025",
  "permintaan_date": "03/06/2025",
  "pengeluaran_code": "abc",
  "pengeluaran_date": "06/08/2025",
  "unit_name": "Kantor Pusat",
  "vendor_name": "VENDOR A",
  "doc_status": "2",
  "keterangan": "testbaru3",
  "file_ttd": "http://localhost:8000/file_bukti_ttd_penerimaan_apd/file_bukti_ttd_penerimaan_apd/1749461159_6846a8a7373ea.jpeg",
  "filename_ttd": "1749461159_6846a8a7373ea.jpeg",
  "doc_date": "09/06/2025 00:00",
  "daftar_penerimaan": [
    {
      "id": "01jxa05ka0anj115rkhsjthw0q",
      "apd_id": "01jx6tpxkwghf6gp62sq27ng64",
      "apd_name": "SEPATU APD",
      "qty": 1
    }
  ]
} 
*/

  String? id;
  String? createdAt;
  String? permintaanCode;
  String? permintaanDate;
  String? pengeluaranCode;
  String? pengeluaranDate;
  String? unitName;
  String? vendorName;
  String? docStatus;
  String? keterangan;
  String? fileTtd;
  String? filenameTtd;
  String? docDate;
  List<ApdReceptionViewModelDataDaftarPenerimaan?>? daftarPenerimaan;

  ApdReceptionViewModelData({
    this.id,
    this.createdAt,
    this.permintaanCode,
    this.permintaanDate,
    this.pengeluaranCode,
    this.pengeluaranDate,
    this.unitName,
    this.vendorName,
    this.docStatus,
    this.keterangan,
    this.fileTtd,
    this.filenameTtd,
    this.docDate,
    this.daftarPenerimaan,
  });
  ApdReceptionViewModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    createdAt = json['created_at']?.toString();
    permintaanCode = json['permintaan_code']?.toString();
    permintaanDate = json['permintaan_date']?.toString();
    pengeluaranCode = json['pengeluaran_code']?.toString();
    pengeluaranDate = json['pengeluaran_date']?.toString();
    unitName = json['unit_name']?.toString();
    vendorName = json['vendor_name']?.toString();
    docStatus = json['doc_status']?.toString();
    keterangan = json['keterangan']?.toString();
    fileTtd = json['file_ttd']?.toString();
    filenameTtd = json['filename_ttd']?.toString();
    docDate = json['doc_date']?.toString();
  if (json['daftar_penerimaan'] != null) {
  final v = json['daftar_penerimaan'];
  final arr0 = <ApdReceptionViewModelDataDaftarPenerimaan>[];
  v.forEach((v) {
  arr0.add(ApdReceptionViewModelDataDaftarPenerimaan.fromJson(v));
  });
    daftarPenerimaan = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['created_at'] = createdAt;
    data['permintaan_code'] = permintaanCode;
    data['permintaan_date'] = permintaanDate;
    data['pengeluaran_code'] = pengeluaranCode;
    data['pengeluaran_date'] = pengeluaranDate;
    data['unit_name'] = unitName;
    data['vendor_name'] = vendorName;
    data['doc_status'] = docStatus;
    data['keterangan'] = keterangan;
    data['file_ttd'] = fileTtd;
    data['filename_ttd'] = filenameTtd;
    data['doc_date'] = docDate;
    if (daftarPenerimaan != null) {
      final v = daftarPenerimaan;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['daftar_penerimaan'] = arr0;
    }
    return data;
  }
}

class ApdReceptionViewModel {
/*
{
  "data": {
    "id": "01jxa05k9xhea0sheaseza9vd9",
    "created_at": "09/06/2025",
    "permintaan_code": "000/REQ/K3L-MKP/VI/2025",
    "permintaan_date": "03/06/2025",
    "pengeluaran_code": "abc",
    "pengeluaran_date": "06/08/2025",
    "unit_name": "Kantor Pusat",
    "vendor_name": "VENDOR A",
    "doc_status": "2",
    "keterangan": "testbaru3",
    "file_ttd": "http://localhost:8000/file_bukti_ttd_penerimaan_apd/file_bukti_ttd_penerimaan_apd/1749461159_6846a8a7373ea.jpeg",
    "filename_ttd": "1749461159_6846a8a7373ea.jpeg",
    "doc_date": "09/06/2025 00:00",
    "daftar_penerimaan": [
      {
        "id": "01jxa05ka0anj115rkhsjthw0q",
        "apd_id": "01jx6tpxkwghf6gp62sq27ng64",
        "apd_name": "SEPATU APD",
        "qty": 1
      }
    ]
  },
  "message": "Data berhasil diambil",
  "status": true
} 
*/

  ApdReceptionViewModelData? data;
  String? message;
  bool? status;

  ApdReceptionViewModel({
    this.data,
    this.message,
    this.status,
  });
  ApdReceptionViewModel.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null) ? ApdReceptionViewModelData.fromJson(json['data']) : null;
    message = json['message']?.toString();
    status = json['status'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}
