///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ApdReceptionViewModelDataGambarPenerimaan {
/*
{
  "id": "01jynecswpb8pf4nwyfj7kwqsg",
  "file": "https://mkp-k3l.erdata.id/file_bukti_foto_penerimaan_apd/1750918915_685ce703f1a9e.jpeg",
  "filename": "1750918915_685ce703f1a9e.jpeg"
} 
*/

  String? id;
  String? file;
  String? filename;

  ApdReceptionViewModelDataGambarPenerimaan({
    this.id,
    this.file,
    this.filename,
  });
  ApdReceptionViewModelDataGambarPenerimaan.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    file = json['file']?.toString();
    filename = json['filename']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['file'] = file;
    data['filename'] = filename;
    return data;
  }
}

class ApdReceptionViewModelDataDaftarPenerimaan {
/*
{
  "id": "01jynecswcnjvqyerzwfkkmssh",
  "apd_id": "01jxakar5jxvj9m51y0bremh1a",
  "apd_name": "Sepatu Safety",
  "apd_code": "APD-000/TES-SEPATU-001",
  "qty_diterima": 55,
  "qty_sisa": 5,
  "qty_jumlah": 25,
  "warna": "-",
  "ukuran_baju": "-",
  "ukuran_celana": "-",
  "ukuran_sepatu": "39",
  "jenis_sepatu": "Short",
  "kategori_apd": "TES SEPATU",
  "kategori_id": "01jxak8vn4sz3ryagpkjj5krr0"
} 
*/

  String? id;
  String? apdId;
  String? apdName;
  String? apdCode;
  int? qtyDiterima;
  int? qtySisa;
  int? qtyJumlah;
  String? warna;
  String? ukuranBaju;
  String? ukuranCelana;
  String? ukuranSepatu;
  String? jenisSepatu;
  String? kategoriApd;
  String? kategoriId;

  ApdReceptionViewModelDataDaftarPenerimaan({
    this.id,
    this.apdId,
    this.apdName,
    this.apdCode,
    this.qtyDiterima,
    this.qtySisa,
    this.qtyJumlah,
    this.warna,
    this.ukuranBaju,
    this.ukuranCelana,
    this.ukuranSepatu,
    this.jenisSepatu,
    this.kategoriApd,
    this.kategoriId,
  });
  ApdReceptionViewModelDataDaftarPenerimaan.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    apdId = json['apd_id']?.toString();
    apdName = json['apd_name']?.toString();
    apdCode = json['apd_code']?.toString();
    qtyDiterima = json['qty_diterima']?.toInt();
    qtySisa = json['qty_sisa']?.toInt();
    qtyJumlah = json['qty_jumlah']?.toInt();
    warna = json['warna']?.toString();
    ukuranBaju = json['ukuran_baju']?.toString();
    ukuranCelana = json['ukuran_celana']?.toString();
    ukuranSepatu = json['ukuran_sepatu']?.toString();
    jenisSepatu = json['jenis_sepatu']?.toString();
    kategoriApd = json['kategori_apd']?.toString();
    kategoriId = json['kategori_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['apd_id'] = apdId;
    data['apd_name'] = apdName;
    data['apd_code'] = apdCode;
    data['qty_diterima'] = qtyDiterima;
    data['qty_sisa'] = qtySisa;
    data['qty_jumlah'] = qtyJumlah;
    data['warna'] = warna;
    data['ukuran_baju'] = ukuranBaju;
    data['ukuran_celana'] = ukuranCelana;
    data['ukuran_sepatu'] = ukuranSepatu;
    data['jenis_sepatu'] = jenisSepatu;
    data['kategori_apd'] = kategoriApd;
    data['kategori_id'] = kategoriId;
    return data;
  }
}

class ApdReceptionViewModelData {
/*
{
  "id": "01jynecsw7xaf4hbx20w9g9pdb",
  "created_at": "26/06/2025",
  "permintaan_code": "000/REQ/K3L-MKP/I/1970",
  "permintaan_id": "01jxvq9d5eg91rqvt0cv017m3x",
  "permintaan_date": "01/01/1970",
  "pengeluaran_code": "004/GI/K3L-MKP/VI/2025",
  "pengeluaran_id": "01jxfmj11dj2hrt80x7xttd52w",
  "pengeluaran_date": "11/06/2025",
  "unit_name": "Kantor Pusat",
  "vendor_name": "CV Alkas Triyasa Adhimukti",
  "doc_status": "2",
  "keterangan": "adadd",
  "file_ttd": "https://mkp-k3l.erdata.id/file_bukti_ttd_penerimaan_apd/1750918915_685ce703edd46.jpeg",
  "filename_ttd": "1750918915_685ce703edd46.jpeg",
  "user_name": "Admin K3",
  "longitude": "-122.08400000000002",
  "latitude": "37.421998333333335",
  "doc_date": "26/06/2025 00:00",
  "daftar_penerimaan": [
    {
      "id": "01jynecswcnjvqyerzwfkkmssh",
      "apd_id": "01jxakar5jxvj9m51y0bremh1a",
      "apd_name": "Sepatu Safety",
      "apd_code": "APD-000/TES-SEPATU-001",
      "qty_diterima": 55,
      "qty_sisa": 5,
      "qty_jumlah": 25,
      "warna": "-",
      "ukuran_baju": "-",
      "ukuran_celana": "-",
      "ukuran_sepatu": "39",
      "jenis_sepatu": "Short",
      "kategori_apd": "TES SEPATU",
      "kategori_id": "01jxak8vn4sz3ryagpkjj5krr0"
    }
  ],
  "gambar_penerimaan": [
    {
      "id": "01jynecswpb8pf4nwyfj7kwqsg",
      "file": "https://mkp-k3l.erdata.id/file_bukti_foto_penerimaan_apd/1750918915_685ce703f1a9e.jpeg",
      "filename": "1750918915_685ce703f1a9e.jpeg"
    }
  ]
} 
*/

  String? id;
  String? createdAt;
  String? permintaanCode;
  String? permintaanId;
  String? permintaanDate;
  String? pengeluaranCode;
  String? pengeluaranId;
  String? pengeluaranDate;
  String? unitName;
  String? vendorName;
  String? docStatus;
  String? keterangan;
  String? fileTtd;
  String? filenameTtd;
  String? userName;
  String? longitude;
  String? latitude;
  String? docDate;
  List<ApdReceptionViewModelDataDaftarPenerimaan?>? daftarPenerimaan;
  List<ApdReceptionViewModelDataGambarPenerimaan?>? gambarPenerimaan;

  ApdReceptionViewModelData({
    this.id,
    this.createdAt,
    this.permintaanCode,
    this.permintaanId,
    this.permintaanDate,
    this.pengeluaranCode,
    this.pengeluaranId,
    this.pengeluaranDate,
    this.unitName,
    this.vendorName,
    this.docStatus,
    this.keterangan,
    this.fileTtd,
    this.filenameTtd,
    this.userName,
    this.longitude,
    this.latitude,
    this.docDate,
    this.daftarPenerimaan,
    this.gambarPenerimaan,
  });
  ApdReceptionViewModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    createdAt = json['created_at']?.toString();
    permintaanCode = json['permintaan_code']?.toString();
    permintaanId = json['permintaan_id']?.toString();
    permintaanDate = json['permintaan_date']?.toString();
    pengeluaranCode = json['pengeluaran_code']?.toString();
    pengeluaranId = json['pengeluaran_id']?.toString();
    pengeluaranDate = json['pengeluaran_date']?.toString();
    unitName = json['unit_name']?.toString();
    vendorName = json['vendor_name']?.toString();
    docStatus = json['doc_status']?.toString();
    keterangan = json['keterangan']?.toString();
    fileTtd = json['file_ttd']?.toString();
    filenameTtd = json['filename_ttd']?.toString();
    userName = json['user_name']?.toString();
    longitude = json['longitude']?.toString();
    latitude = json['latitude']?.toString();
    docDate = json['doc_date']?.toString();
  if (json['daftar_penerimaan'] != null) {
  final v = json['daftar_penerimaan'];
  final arr0 = <ApdReceptionViewModelDataDaftarPenerimaan>[];
  v.forEach((v) {
  arr0.add(ApdReceptionViewModelDataDaftarPenerimaan.fromJson(v));
  });
    daftarPenerimaan = arr0;
    }
  if (json['gambar_penerimaan'] != null) {
  final v = json['gambar_penerimaan'];
  final arr0 = <ApdReceptionViewModelDataGambarPenerimaan>[];
  v.forEach((v) {
  arr0.add(ApdReceptionViewModelDataGambarPenerimaan.fromJson(v));
  });
    gambarPenerimaan = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['created_at'] = createdAt;
    data['permintaan_code'] = permintaanCode;
    data['permintaan_id'] = permintaanId;
    data['permintaan_date'] = permintaanDate;
    data['pengeluaran_code'] = pengeluaranCode;
    data['pengeluaran_id'] = pengeluaranId;
    data['pengeluaran_date'] = pengeluaranDate;
    data['unit_name'] = unitName;
    data['vendor_name'] = vendorName;
    data['doc_status'] = docStatus;
    data['keterangan'] = keterangan;
    data['file_ttd'] = fileTtd;
    data['filename_ttd'] = filenameTtd;
    data['user_name'] = userName;
    data['longitude'] = longitude;
    data['latitude'] = latitude;
    data['doc_date'] = docDate;
    if (daftarPenerimaan != null) {
      final v = daftarPenerimaan;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['daftar_penerimaan'] = arr0;
    }
    if (gambarPenerimaan != null) {
      final v = gambarPenerimaan;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['gambar_penerimaan'] = arr0;
    }
    return data;
  }
}

class ApdReceptionViewModel {
/*
{
  "data": {
    "id": "01jynecsw7xaf4hbx20w9g9pdb",
    "created_at": "26/06/2025",
    "permintaan_code": "000/REQ/K3L-MKP/I/1970",
    "permintaan_id": "01jxvq9d5eg91rqvt0cv017m3x",
    "permintaan_date": "01/01/1970",
    "pengeluaran_code": "004/GI/K3L-MKP/VI/2025",
    "pengeluaran_id": "01jxfmj11dj2hrt80x7xttd52w",
    "pengeluaran_date": "11/06/2025",
    "unit_name": "Kantor Pusat",
    "vendor_name": "CV Alkas Triyasa Adhimukti",
    "doc_status": "2",
    "keterangan": "adadd",
    "file_ttd": "https://mkp-k3l.erdata.id/file_bukti_ttd_penerimaan_apd/1750918915_685ce703edd46.jpeg",
    "filename_ttd": "1750918915_685ce703edd46.jpeg",
    "user_name": "Admin K3",
    "longitude": "-122.08400000000002",
    "latitude": "37.421998333333335",
    "doc_date": "26/06/2025 00:00",
    "daftar_penerimaan": [
      {
        "id": "01jynecswcnjvqyerzwfkkmssh",
        "apd_id": "01jxakar5jxvj9m51y0bremh1a",
        "apd_name": "Sepatu Safety",
        "apd_code": "APD-000/TES-SEPATU-001",
        "qty_diterima": 55,
        "qty_sisa": 5,
        "qty_jumlah": 25,
        "warna": "-",
        "ukuran_baju": "-",
        "ukuran_celana": "-",
        "ukuran_sepatu": "39",
        "jenis_sepatu": "Short",
        "kategori_apd": "TES SEPATU",
        "kategori_id": "01jxak8vn4sz3ryagpkjj5krr0"
      }
    ],
    "gambar_penerimaan": [
      {
        "id": "01jynecswpb8pf4nwyfj7kwqsg",
        "file": "https://mkp-k3l.erdata.id/file_bukti_foto_penerimaan_apd/1750918915_685ce703f1a9e.jpeg",
        "filename": "1750918915_685ce703f1a9e.jpeg"
      }
    ]
  },
  "message": "Data berhasil diambil",
  "status": true
} 
*/

  ApdReceptionViewModelData? data;
  String? message;
  bool? status;

  ApdReceptionViewModel({
    this.data,
    this.message,
    this.status,
  });
  ApdReceptionViewModel.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null) ? ApdReceptionViewModelData.fromJson(json['data']) : null;
    message = json['message']?.toString();
    status = json['status'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['data'] = this.data!.toJson();
      data['message'] = message;
    data['status'] = status;
    return data;
  }
}
