///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ApdReceptionViewModelDataGambarPenerimaan {
  /*
{
  "id": "01jxbxqv8ahh666ggzbm8kazf6",
  "file": "http://localhost:8000/file_bukti_foto_penerimaan_apd/file_bukti_foto_penerimaan_apd/1749525720_6847a4d85025b.jpeg",
  "filename": "1749525720_6847a4d85025b.jpeg"
} 
*/

  String? id;
  String? file;
  String? filename;

  ApdReceptionViewModelDataGambarPenerimaan({
    this.id,
    this.file,
    this.filename,
  });
  ApdReceptionViewModelDataGambarPenerimaan.fromJson(
    Map<String, dynamic> json,
  ) {
    id = json['id']?.toString();
    file = json['file']?.toString();
    filename = json['filename']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['file'] = file;
    data['filename'] = filename;
    return data;
  }
}

class ApdReceptionViewModelDataDaftarPenerimaan {
  /*
{
  "id": "01jxbxqv837tf0spmvzx00p88g",
  "apd_id": "01jx6tpxkwghf6gp62sq27ng64",
  "apd_name": "SEPATU APD",
  "qty_diterima": 1,
  "qty_sisa": "1",
  "qty_jumlah": 0
} 
*/

  String? id;
  String? apdId;
  String? apdName;
  int? qtyDiterima;
  String? qtySisa;
  int? qtyJumlah;
  String? code;
  String? warna;
  String? ukuranBaju;
  String? ukuranCelana;
  String? ukuranSepatu;
  String? jenisSepatu;

  ApdReceptionViewModelDataDaftarPenerimaan({
    this.id,
    this.apdId,
    this.apdName,
    this.qtyDiterima,
    this.qtySisa,
    this.qtyJumlah,
    this.code,
    this.warna,
    this.ukuranBaju,
    this.ukuranCelana,
    this.ukuranSepatu,
    this.jenisSepatu,
  });
  ApdReceptionViewModelDataDaftarPenerimaan.fromJson(
    Map<String, dynamic> json,
  ) {
    id = json['id']?.toString();
    apdId = json['apd_id']?.toString();
    apdName = json['apd_name']?.toString();
    qtyDiterima = json['qty_diterima']?.toInt();
    qtySisa = json['qty_sisa']?.toString();
    qtyJumlah = json['qty_jumlah']?.toInt();
    code = json['code']?.toString();
    warna = json['warna']?.toString();
    ukuranBaju = json['ukuran_baju']?.toString();
    ukuranCelana = json['ukuran_celana']?.toString();
    ukuranSepatu = json['ukuran_sepatu']?.toString();
    jenisSepatu = json['jenis_sepatu']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['apd_id'] = apdId;
    data['apd_name'] = apdName;
    data['qty_diterima'] = qtyDiterima;
    data['qty_sisa'] = qtySisa;
    data['qty_jumlah'] = qtyJumlah;
    data['code'] = code;
    data['warna'] = warna;
    data['ukuran_baju'] = ukuranBaju;
    data['ukuran_celana'] = ukuranCelana;
    data['ukuran_sepatu'] = ukuranSepatu;
    data['jenis_sepatu'] = jenisSepatu;
    return data;
  }
}

class ApdReceptionViewModelData {
  /*
{
  "id": "01jxbxqv81qdt3bkaaq13jzz0y",
  "created_at": "10/06/2025",
  "permintaan_code": "000/REQ/K3L-MKP/VI/2025",
  "permintaan_date": "03/06/2025",
  "pengeluaran_code": "abc",
  "pengeluaran_date": "06/08/2025",
  "unit_name": "Kantor Pusat",
  "vendor_name": "VENDOR A",
  "doc_status": "2",
  "keterangan": "testbaru4",
  "file_ttd": "http://localhost:8000/file_bukti_ttd_penerimaan_apd/file_bukti_ttd_penerimaan_apd/1749525720_6847a4d84de01.jpeg",
  "filename_ttd": "1749525720_6847a4d84de01.jpeg",
  "doc_date": "10/06/2025 00:00",
  "daftar_penerimaan": [
    {
      "id": "01jxbxqv837tf0spmvzx00p88g",
      "apd_id": "01jx6tpxkwghf6gp62sq27ng64",
      "apd_name": "SEPATU APD",
      "qty_diterima": 1,
      "qty_sisa": "1",
      "qty_jumlah": 0
    }
  ],
  "gambar_penerimaan": [
    {
      "id": "01jxbxqv8ahh666ggzbm8kazf6",
      "file": "http://localhost:8000/file_bukti_foto_penerimaan_apd/file_bukti_foto_penerimaan_apd/1749525720_6847a4d85025b.jpeg",
      "filename": "1749525720_6847a4d85025b.jpeg"
    }
  ]
} 
*/

  String? id;
  String? createdAt;
  String? permintaanCode;
  String? permintaanDate;
  String? pengeluaranCode;
  String? pengeluaranDate;
  String? unitName;
  String? vendorName;
  String? docStatus;
  String? keterangan;
  String? fileTtd;
  String? filenameTtd;
  String? docDate;
  List<ApdReceptionViewModelDataDaftarPenerimaan?>? daftarPenerimaan;
  List<ApdReceptionViewModelDataGambarPenerimaan?>? gambarPenerimaan;

  ApdReceptionViewModelData({
    this.id,
    this.createdAt,
    this.permintaanCode,
    this.permintaanDate,
    this.pengeluaranCode,
    this.pengeluaranDate,
    this.unitName,
    this.vendorName,
    this.docStatus,
    this.keterangan,
    this.fileTtd,
    this.filenameTtd,
    this.docDate,
    this.daftarPenerimaan,
    this.gambarPenerimaan,
  });
  ApdReceptionViewModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    createdAt = json['created_at']?.toString();
    permintaanCode = json['permintaan_code']?.toString();
    permintaanDate = json['permintaan_date']?.toString();
    pengeluaranCode = json['pengeluaran_code']?.toString();
    pengeluaranDate = json['pengeluaran_date']?.toString();
    unitName = json['unit_name']?.toString();
    vendorName = json['vendor_name']?.toString();
    docStatus = json['doc_status']?.toString();
    keterangan = json['keterangan']?.toString();
    fileTtd = json['file_ttd']?.toString();
    filenameTtd = json['filename_ttd']?.toString();
    docDate = json['doc_date']?.toString();
    if (json['daftar_penerimaan'] != null) {
      final v = json['daftar_penerimaan'];
      final arr0 = <ApdReceptionViewModelDataDaftarPenerimaan>[];
      v.forEach((v) {
        arr0.add(ApdReceptionViewModelDataDaftarPenerimaan.fromJson(v));
      });
      daftarPenerimaan = arr0;
    }
    if (json['gambar_penerimaan'] != null) {
      final v = json['gambar_penerimaan'];
      final arr0 = <ApdReceptionViewModelDataGambarPenerimaan>[];
      v.forEach((v) {
        arr0.add(ApdReceptionViewModelDataGambarPenerimaan.fromJson(v));
      });
      gambarPenerimaan = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['created_at'] = createdAt;
    data['permintaan_code'] = permintaanCode;
    data['permintaan_date'] = permintaanDate;
    data['pengeluaran_code'] = pengeluaranCode;
    data['pengeluaran_date'] = pengeluaranDate;
    data['unit_name'] = unitName;
    data['vendor_name'] = vendorName;
    data['doc_status'] = docStatus;
    data['keterangan'] = keterangan;
    data['file_ttd'] = fileTtd;
    data['filename_ttd'] = filenameTtd;
    data['doc_date'] = docDate;
    if (daftarPenerimaan != null) {
      final v = daftarPenerimaan;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['daftar_penerimaan'] = arr0;
    }
    if (gambarPenerimaan != null) {
      final v = gambarPenerimaan;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['gambar_penerimaan'] = arr0;
    }
    return data;
  }
}

class ApdReceptionViewModel {
  /*
{
  "data": {
    "id": "01jxbxqv81qdt3bkaaq13jzz0y",
    "created_at": "10/06/2025",
    "permintaan_code": "000/REQ/K3L-MKP/VI/2025",
    "permintaan_date": "03/06/2025",
    "pengeluaran_code": "abc",
    "pengeluaran_date": "06/08/2025",
    "unit_name": "Kantor Pusat",
    "vendor_name": "VENDOR A",
    "doc_status": "2",
    "keterangan": "testbaru4",
    "file_ttd": "http://localhost:8000/file_bukti_ttd_penerimaan_apd/file_bukti_ttd_penerimaan_apd/1749525720_6847a4d84de01.jpeg",
    "filename_ttd": "1749525720_6847a4d84de01.jpeg",
    "doc_date": "10/06/2025 00:00",
    "daftar_penerimaan": [
      {
        "id": "01jxbxqv837tf0spmvzx00p88g",
        "apd_id": "01jx6tpxkwghf6gp62sq27ng64",
        "apd_name": "SEPATU APD",
        "qty_diterima": 1,
        "qty_sisa": "1",
        "qty_jumlah": 0
      }
    ],
    "gambar_penerimaan": [
      {
        "id": "01jxbxqv8ahh666ggzbm8kazf6",
        "file": "http://localhost:8000/file_bukti_foto_penerimaan_apd/file_bukti_foto_penerimaan_apd/1749525720_6847a4d85025b.jpeg",
        "filename": "1749525720_6847a4d85025b.jpeg"
      }
    ]
  },
  "message": "Data berhasil diambil",
  "status": true
} 
*/

  ApdReceptionViewModelData? data;
  String? message;
  bool? status;

  ApdReceptionViewModel({this.data, this.message, this.status});
  ApdReceptionViewModel.fromJson(Map<String, dynamic> json) {
    data =
        (json['data'] != null)
            ? ApdReceptionViewModelData.fromJson(json['data'])
            : null;
    message = json['message']?.toString();
    status = json['status'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}
