///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ApdReceptionParamDataApdReceive {
/*
{
  "id": "01jwbfjgzb6z87mwgnxvf3315p",
  "qty": 1
} 
*/

  String? id;
  String? code;
  String? name;
  int? qty;
  int? receivedQty;

  ApdReceptionParamDataApdReceive({
    this.id,
    this.code,
    this.name,
    this.qty,
    this.receivedQty,
  });
  ApdReceptionParamDataApdReceive.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    qty = json['qty']?.toInt();
    // receivedQty = json['received_qty']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['qty'] = qty;
    return data;
  }
}

class ApdReceptionParam {
/*
{
  "doc_date": "2025-04-21 00:00:00",
  "permintaan_id": "01jx74qh74045zrkdm0ccch8p0",
  "pengeluaran_id": "01jx74qh74045zrkdm0ccch8p0",
  "keterangan": "wiwok",
  "data_apd_receive": [
    {
      "id": "01jwbfjgzb6z87mwgnxvf3315p",
      "qty": 1
    }
  ],
  "bukti_foto": "data:image/jpeg;base64",
  "ttd_foto": "data:image/jpeg;base64",
  "action": "draft"
} 
*/

  String? docDate;
  String? permintaanId;
  String? pengeluaranId;
  String? keterangan;
  List<ApdReceptionParamDataApdReceive?>? dataApdReceive;
  String? buktiFoto;
  String? ttdFoto;
  String? action;

  ApdReceptionParam({
    this.docDate,
    this.permintaanId,
    this.pengeluaranId,
    this.keterangan,
    this.dataApdReceive,
    this.buktiFoto,
    this.ttdFoto,
    this.action,
  });
  ApdReceptionParam.fromJson(Map<String, dynamic> json) {
    docDate = json['doc_date']?.toString();
    permintaanId = json['permintaan_id']?.toString();
    pengeluaranId = json['pengeluaran_id']?.toString();
    keterangan = json['keterangan']?.toString();
  if (json['data_apd_receive'] != null) {
  final v = json['data_apd_receive'];
  final arr0 = <ApdReceptionParamDataApdReceive>[];
  v.forEach((v) {
  arr0.add(ApdReceptionParamDataApdReceive.fromJson(v));
  });
    dataApdReceive = arr0;
    }
    buktiFoto = json['bukti_foto']?.toString();
    ttdFoto = json['ttd_foto']?.toString();
    action = json['action']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['doc_date'] = docDate;
    data['permintaan_id'] = permintaanId;
    data['pengeluaran_id'] = pengeluaranId;
    data['keterangan'] = keterangan;
    if (dataApdReceive != null) {
      final v = dataApdReceive;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['data_apd_receive'] = arr0;
    }
    data['bukti_foto'] = buktiFoto;
    data['ttd_foto'] = ttdFoto;
    data['action'] = action;
    return data;
  }
}
