///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class HomeModelDataLinimasa {
/*
{
  "id": "01jx6vkymgh1k183egrbzwr8p0",
  "created_date": "08/06/2025",
  "created_time": "04:08",
  "code": "Permintaan APD : 000/REQ/K3L-MKP/VI/2025",
  "description": "wuwuwu"
} 
*/

  String? id;
  String? createdDate;
  String? createdTime;
  String? code;
  String? description;

  HomeModelDataLinimasa({
    this.id,
    this.createdDate,
    this.createdTime,
    this.code,
    this.description,
  });
  HomeModelDataLinimasa.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    createdDate = json['created_date']?.toString();
    createdTime = json['created_time']?.toString();
    code = json['code']?.toString();
    description = json['description']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['created_date'] = createdDate;
    data['created_time'] = createdTime;
    data['code'] = code;
    data['description'] = description;
    return data;
  }
}

class HomeModelDataManajemenApd {
/*
{
  "permintaan": 2,
  "penerimaan": 1,
  "pengembalian": 1
} 
*/

  String? permintaan;
  String? penerimaan;
  String? pengembalian;

  HomeModelDataManajemenApd({
    this.permintaan,
    this.penerimaan,
    this.pengembalian,
  });
  HomeModelDataManajemenApd.fromJson(Map<String, dynamic> json) {
    permintaan = json['permintaan']?.toString();
    penerimaan = json['penerimaan']?.toString();
    pengembalian = json['pengembalian']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['permintaan'] = permintaan;
    data['penerimaan'] = penerimaan;
    data['pengembalian'] = pengembalian;
    return data;
  }
}

class HomeModelDataInspeksi {
/*
{
  "rutin": 1,
  "proyek": 1
} 
*/

  String? rutin;
  String? proyek;

  HomeModelDataInspeksi({
    this.rutin,
    this.proyek,
  });
  HomeModelDataInspeksi.fromJson(Map<String, dynamic> json) {
    rutin = json['rutin']?.toString();
    proyek = json['proyek']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['rutin'] = rutin;
    data['proyek'] = proyek;
    return data;
  }
}

class HomeModelData {
/*
{
  "inspeksi": {
    "rutin": 1,
    "proyek": 1
  },
  "manajemen_apd": {
    "permintaan": 2,
    "penerimaan": 1,
    "pengembalian": 1
  },
  "linimasa": [
    {
      "id": "01jx6vkymgh1k183egrbzwr8p0",
      "created_date": "08/06/2025",
      "created_time": "04:08",
      "code": "Permintaan APD : 000/REQ/K3L-MKP/VI/2025",
      "description": "wuwuwu"
    }
  ]
} 
*/

  HomeModelDataInspeksi? inspeksi;
  HomeModelDataManajemenApd? manajemenApd;
  List<HomeModelDataLinimasa?>? linimasa;

  HomeModelData({
    this.inspeksi,
    this.manajemenApd,
    this.linimasa,
  });
  HomeModelData.fromJson(Map<String, dynamic> json) {
    inspeksi = (json['inspeksi'] != null) ? HomeModelDataInspeksi.fromJson(json['inspeksi']) : null;
    manajemenApd = (json['manajemen_apd'] != null) ? HomeModelDataManajemenApd.fromJson(json['manajemen_apd']) : null;
  if (json['linimasa'] != null) {
  final v = json['linimasa'];
  final arr0 = <HomeModelDataLinimasa>[];
  v.forEach((v) {
  arr0.add(HomeModelDataLinimasa.fromJson(v));
  });
    linimasa = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (inspeksi != null) {
      data['inspeksi'] = inspeksi!.toJson();
    }
    if (manajemenApd != null) {
      data['manajemen_apd'] = manajemenApd!.toJson();
    }
    if (linimasa != null) {
      final v = linimasa;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['linimasa'] = arr0;
    }
    return data;
  }
}

class HomeModel {
/*
{
  "data": {
    "inspeksi": {
      "rutin": 1,
      "proyek": 1
    },
    "manajemen_apd": {
      "permintaan": 2,
      "penerimaan": 1,
      "pengembalian": 1
    },
    "linimasa": [
      {
        "id": "01jx6vkymgh1k183egrbzwr8p0",
        "created_date": "08/06/2025",
        "created_time": "04:08",
        "code": "Permintaan APD : 000/REQ/K3L-MKP/VI/2025",
        "description": "wuwuwu"
      }
    ]
  },
  "message": "Data berhasil dimuat",
  "status": true
} 
*/

  HomeModelData? data;
  String? message;
  bool? status;

  HomeModel({
    this.data,
    this.message,
    this.status,
  });
  HomeModel.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null) ? HomeModelData.fromJson(json['data']) : null;
    message = json['message']?.toString();
    status = json['status'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['data'] = this.data!.toJson();
      data['message'] = message;
    data['status'] = status;
    return data;
  }
}
