///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ApdSelectModelData {
/*
{
  "id": "01jx6tpxkwghf6gp62sq27ng64",
  "code": "APD-000/WOM",
  "name": "SEPATU APD"
} 
*/

  String? id;
  String? code;
  String? name;

  ApdSelectModelData({
    this.id,
    this.code,
    this.name,
  });
  ApdSelectModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    code = json['code']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['code'] = code;
    data['name'] = name;
    return data;
  }
}

class ApdSelectModel {
/*
{
  "data": [
    {
      "id": "01jx6tpxkwghf6gp62sq27ng64",
      "code": "APD-000/WOM",
      "name": "SEPATU APD"
    }
  ],
  "message": "Data berhasil diambil",
  "status": true
} 
*/

  List<ApdSelectModelData?>? data;
  String? message;
  bool? status;

  ApdSelectModel({
    this.data,
    this.message,
    this.status,
  });
  ApdSelectModel.fromJson(Map<String, dynamic> json) {
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <ApdSelectModelData>[];
  v.forEach((v) {
  arr0.add(ApdSelectModelData.fromJson(v));
  });
    this.data = arr0;
    }
    message = json['message']?.toString();
    status = json['status'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['data'] = arr0;
    }
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}
