///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ExpenditureSelectModelDataDetailPengeluaran {
/*
{
  "id": "01jyjjy7bzkv0hh2csc7fb3q5f",
  "apd_name": "SEPATU APD",
  "apd_id": "01jx6tpxkwghf6gp62sq27ng64",
  "qty_available": 2
} 
*/

  String? id;
  String? apdName;
  String? apdId;
  int? qtyAvailable;

  ExpenditureSelectModelDataDetailPengeluaran({
    this.id,
    this.apdName,
    this.apdId,
    this.qtyAvailable,
  });
  ExpenditureSelectModelDataDetailPengeluaran.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    apdName = json['apd_name']?.toString();
    apdId = json['apd_id']?.toString();
    qtyAvailable = json['qty_available']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['apd_name'] = apdName;
    data['apd_id'] = apdId;
    data['qty_available'] = qtyAvailable;
    return data;
  }
}

class ExpenditureSelectModelData {
/*
{
  "id": "01jx74qh74045zrkdm0ccch8p0",
  "doc_date": "06/08/2025",
  "code": "abc",
  "vendor_name": "VENDOR A",
  "vendor_id": "01jx76kr3feq6chz4fzv96v2tj",
  "request_code": "001/REQ/K3L-MKP/VI/2025",
  "deskripsi": "abc",
  "status": "Disetujui",
  "detail_pengeluaran": [
    {
      "id": "01jyjjy7bzkv0hh2csc7fb3q5f",
      "apd_name": "SEPATU APD",
      "apd_id": "01jx6tpxkwghf6gp62sq27ng64",
      "qty_available": 2
    }
  ]
} 
*/

  String? id;
  String? docDate;
  String? code;
  String? vendorName;
  String? vendorId;
  String? requestCode;
  String? deskripsi;
  String? status;
  List<ExpenditureSelectModelDataDetailPengeluaran?>? detailPengeluaran;

  ExpenditureSelectModelData({
    this.id,
    this.docDate,
    this.code,
    this.vendorName,
    this.vendorId,
    this.requestCode,
    this.deskripsi,
    this.status,
    this.detailPengeluaran,
  });
  ExpenditureSelectModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    docDate = json['doc_date']?.toString();
    code = json['code']?.toString();
    vendorName = json['vendor_name']?.toString();
    vendorId = json['vendor_id']?.toString();
    requestCode = json['request_code']?.toString();
    deskripsi = json['deskripsi']?.toString();
    status = json['status']?.toString();
  if (json['detail_pengeluaran'] != null) {
  final v = json['detail_pengeluaran'];
  final arr0 = <ExpenditureSelectModelDataDetailPengeluaran>[];
  v.forEach((v) {
  arr0.add(ExpenditureSelectModelDataDetailPengeluaran.fromJson(v));
  });
    detailPengeluaran = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['doc_date'] = docDate;
    data['code'] = code;
    data['vendor_name'] = vendorName;
    data['vendor_id'] = vendorId;
    data['request_code'] = requestCode;
    data['deskripsi'] = deskripsi;
    data['status'] = status;
    if (detailPengeluaran != null) {
      final v = detailPengeluaran;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['detail_pengeluaran'] = arr0;
    }
    return data;
  }
}

class ExpenditureSelectModel {
/*
{
  "data": [
    {
      "id": "01jx74qh74045zrkdm0ccch8p0",
      "doc_date": "06/08/2025",
      "code": "abc",
      "vendor_name": "VENDOR A",
      "vendor_id": "01jx76kr3feq6chz4fzv96v2tj",
      "request_code": "001/REQ/K3L-MKP/VI/2025",
      "deskripsi": "abc",
      "status": "Disetujui",
      "detail_pengeluaran": [
        {
          "id": "01jyjjy7bzkv0hh2csc7fb3q5f",
          "apd_name": "SEPATU APD",
          "apd_id": "01jx6tpxkwghf6gp62sq27ng64",
          "qty_available": 2
        }
      ]
    }
  ],
  "message": "Data berhasil diambil",
  "status": true
} 
*/

  List<ExpenditureSelectModelData?>? data;
  String? message;
  bool? status;

  ExpenditureSelectModel({
    this.data,
    this.message,
    this.status,
  });
  ExpenditureSelectModel.fromJson(Map<String, dynamic> json) {
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <ExpenditureSelectModelData>[];
  v.forEach((v) {
  arr0.add(ExpenditureSelectModelData.fromJson(v));
  });
    this.data = arr0;
    }
    message = json['message']?.toString();
    status = json['status'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['data'] = arr0;
    }
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}
