///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ExpenditureSelectModelData {
  /*
{
  "id": "01jx74qh74045zrkdm0ccch8p0",
  "doc_date": "06/08/2025",
  "code": "abc",
  "vendor_name": "VENDOR A",
  "vendor_id": "01jx76kr3feq6chz4fzv96v2tj",
  "request_code": "001/REQ/K3L-MKP/VI/2025",
  "deskripsi": "abc",
  "status": "Disetujui"
} 
*/

  String? id;
  String? docDate;
  String? code;
  String? vendorName;
  String? vendorId;
  String? requestCode;
  String? deskripsi;
  String? status;

  ExpenditureSelectModelData({
    this.id,
    this.docDate,
    this.code,
    this.vendorName,
    this.vendorId,
    this.requestCode,
    this.deskripsi,
    this.status,
  });
  ExpenditureSelectModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    docDate = json['doc_date']?.toString();
    code = json['code']?.toString();
    vendorName = json['vendor_name']?.toString();
    vendorId = json['vendor_id']?.toString();
    requestCode = json['request_code']?.toString();
    deskripsi = json['deskripsi']?.toString();
    status = json['status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['doc_date'] = docDate;
    data['code'] = code;
    data['vendor_name'] = vendorName;
    data['vendor_id'] = vendorId;
    data['request_code'] = requestCode;
    data['deskripsi'] = deskripsi;
    data['status'] = status;
    return data;
  }
}

class ExpenditureSelectModel {
  /*
{
  "data": [
    {
      "id": "01jx74qh74045zrkdm0ccch8p0",
      "doc_date": "06/08/2025",
      "code": "abc",
      "vendor_name": "VENDOR A",
      "vendor_id": "01jx76kr3feq6chz4fzv96v2tj",
      "request_code": "001/REQ/K3L-MKP/VI/2025",
      "deskripsi": "abc",
      "status": "Disetujui"
    }
  ],
  "message": "Data berhasil diambil",
  "status": true
} 
*/

  List<ExpenditureSelectModelData?>? data;
  String? message;
  bool? status;

  ExpenditureSelectModel({this.data, this.message, this.status});
  ExpenditureSelectModel.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <ExpenditureSelectModelData>[];
      v.forEach((v) {
        arr0.add(ExpenditureSelectModelData.fromJson(v));
      });
      this.data = arr0;
    }
    message = json['message']?.toString();
    status = json['status'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}
