///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class InspectionModelData {
  /*
{
  "id": "01jzs7cnva0fggbhn6ejhxv41g",
  "created_at": "10/07/2025",
  "code": "001/F.INS-NM/K3L-MKP/X/2025",
  "type": "0",
  "kategori_name": "Near Miss",
  "doc_status": "0",
  "lokasi": "lokasibos",
  "resiko": "Resikobos",
  "petugas": "Super Admin K3",
  "longitude": "",
  "latitude": "null",
  "doc_date": "07/10/2025 10:51",
  "link_pdf": "https://mkp-k3l.erdata.id/get-pdf-inspeksi/01jzs7cnva0fggbhn6ejhxv41g"
} 
*/

  String? id;
  String? createdAt;
  String? code;
  String? type;
  String? kategoriName;
  String? docStatus;
  String? lokasi;
  String? resiko;
  String? petugas;
  String? longitude;
  String? latitude;
  String? docDate;
  String? linkPdf;

  InspectionModelData({
    this.id,
    this.createdAt,
    this.code,
    this.type,
    this.kategoriName,
    this.docStatus,
    this.lokasi,
    this.resiko,
    this.petugas,
    this.longitude,
    this.latitude,
    this.docDate,
    this.linkPdf,
  });
  InspectionModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    createdAt = json['created_at']?.toString();
    code = json['code']?.toString();
    type = json['type']?.toString();
    kategoriName = json['kategori_name']?.toString();
    docStatus = json['doc_status']?.toString();
    lokasi = json['lokasi']?.toString();
    resiko = json['resiko']?.toString();
    petugas = json['petugas']?.toString();
    longitude = json['longitude']?.toString();
    latitude = json['latitude']?.toString();
    docDate = json['doc_date']?.toString();
    linkPdf = json['link_pdf']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['created_at'] = createdAt;
    data['code'] = code;
    data['type'] = type;
    data['kategori_name'] = kategoriName;
    data['doc_status'] = docStatus;
    data['lokasi'] = lokasi;
    data['resiko'] = resiko;
    data['petugas'] = petugas;
    data['longitude'] = longitude;
    data['latitude'] = latitude;
    data['doc_date'] = docDate;
    data['link_pdf'] = linkPdf;
    return data;
  }
}

class InspectionModel {
  /*
{
  "data": [
    {
      "id": "01jzs7cnva0fggbhn6ejhxv41g",
      "created_at": "10/07/2025",
      "code": "001/F.INS-NM/K3L-MKP/X/2025",
      "type": "0",
      "kategori_name": "Near Miss",
      "doc_status": "0",
      "lokasi": "lokasibos",
      "resiko": "Resikobos",
      "petugas": "Super Admin K3",
      "longitude": "",
      "latitude": "null",
      "doc_date": "07/10/2025 10:51",
      "link_pdf": "https://mkp-k3l.erdata.id/get-pdf-inspeksi/01jzs7cnva0fggbhn6ejhxv41g"
    }
  ],
  "message": "Data berhasil diambil",
  "status": true
} 
*/

  List<InspectionModelData?>? data;
  String? message;
  bool? status;

  InspectionModel({this.data, this.message, this.status});
  InspectionModel.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <InspectionModelData>[];
      v.forEach((v) {
        arr0.add(InspectionModelData.fromJson(v));
      });
      this.data = arr0;
    }
    message = json['message']?.toString();
    status = json['status'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}
