///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class InspectionViewModelDataBuktiFoto {
  /*
{
  "id": "01jyjeavr4zpxq6tdxgkfwrf0d",
  "file": "http://10.0.2.2:8000/file_detail_inspeksi/1750818189_685b5d8d0de45.jpeg",
  "file_name": "1750818189_685b5d8d0de45.jpeg"
} 
*/

  String? id;
  String? file;
  String? fileName;

  InspectionViewModelDataBuktiFoto({this.id, this.file, this.fileName});
  InspectionViewModelDataBuktiFoto.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    file = json['file']?.toString();
    fileName = json['file_name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['file'] = file;
    data['file_name'] = fileName;
    return data;
  }
}

class InspectionViewModelData {
  /*
{
  "id": "01jyjeavnmb7wxd8rz3f043fcs",
  "created_at": "25/06/2025",
  "code": "006/F.INS-UA/K3L-MKP/I/1970",
  "type": "0",
  "kategori_name": "null",
  "kategori_id": "01jx5m22bpq176mbhn07g79eal",
  "doc_status": "0",
  "lokasi": "a",
  "petugas": "Admin K3",
  "petugas_id": "01jx5m236advexa306q0cyhqee",
  "proyek": "null",
  "unit": "Kantor Pusat",
  "unit_id": "01jx5m230nsp9r160yb6n59g46",
  "doc_date": "01/01/1970 00:00",
  "resiko": "a",
  "kronologi": "a",
  "dilakukan_tindakan": 1,
  "alasan": "null",
  "rincian_tindakan": "a",
  "saran": "a",
  "tindak_lanjut": 0,
  "longitude_latitude": "-122.08400000000002,37.421998333333335",
  "tindakan_tindak_lanjut": "",
  "bukti_foto": [
    {
      "id": "01jyjeavr4zpxq6tdxgkfwrf0d",
      "file": "http://10.0.2.2:8000/file_detail_inspeksi/1750818189_685b5d8d0de45.jpeg",
      "file_name": "1750818189_685b5d8d0de45.jpeg"
    }
  ]
} 
*/

  String? id;
  String? createdAt;
  String? code;
  String? type;
  String? kategoriName;
  String? kategoriId;
  String? docStatus;
  String? lokasi;
  String? petugas;
  String? petugasId;
  String? proyek;
  String? unit;
  String? unitId;
  String? docDate;
  String? resiko;
  String? kronologi;
  int? dilakukanTindakan;
  String? alasan;
  String? rincianTindakan;
  String? saran;
  int? tindakLanjut;
  String? latitude;
  String? longitude;
  String? tindakanTindakLanjut;
  List<InspectionViewModelDataBuktiFoto?>? buktiFoto;

  InspectionViewModelData({
    this.id,
    this.createdAt,
    this.code,
    this.type,
    this.kategoriName,
    this.kategoriId,
    this.docStatus,
    this.lokasi,
    this.petugas,
    this.petugasId,
    this.proyek,
    this.unit,
    this.unitId,
    this.docDate,
    this.resiko,
    this.kronologi,
    this.dilakukanTindakan,
    this.alasan,
    this.rincianTindakan,
    this.saran,
    this.tindakLanjut,
    this.latitude,
    this.longitude,
    this.tindakanTindakLanjut,
    this.buktiFoto,
  });
  InspectionViewModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    createdAt = json['created_at']?.toString();
    code = json['code']?.toString();
    type = json['type']?.toString();
    kategoriName = json['kategori_name']?.toString();
    kategoriId = json['kategori_id']?.toString();
    docStatus = json['doc_status']?.toString();
    lokasi = json['lokasi']?.toString();
    petugas = json['petugas']?.toString();
    petugasId = json['petugas_id']?.toString();
    proyek = json['proyek']?.toString();
    unit = json['unit']?.toString();
    unitId = json['unit_id']?.toString();
    docDate = json['doc_date']?.toString();
    resiko = json['resiko']?.toString();
    kronologi = json['kronologi']?.toString();
    dilakukanTindakan = json['dilakukan_tindakan']?.toInt();
    alasan = json['alasan']?.toString();
    rincianTindakan = json['rincian_tindakan']?.toString();
    saran = json['saran']?.toString();
    tindakLanjut = json['tindak_lanjut']?.toInt();
    latitude = json['latitude']?.toString();
    longitude = json['longitude']?.toString();
    tindakanTindakLanjut = json['tindakan_tindak_lanjut']?.toString();
    if (json['bukti_foto'] != null) {
      final v = json['bukti_foto'];
      final arr0 = <InspectionViewModelDataBuktiFoto>[];
      v.forEach((v) {
        arr0.add(InspectionViewModelDataBuktiFoto.fromJson(v));
      });
      buktiFoto = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['created_at'] = createdAt;
    data['code'] = code;
    data['type'] = type;
    data['kategori_name'] = kategoriName;
    data['kategori_id'] = kategoriId;
    data['doc_status'] = docStatus;
    data['lokasi'] = lokasi;
    data['petugas'] = petugas;
    data['petugas_id'] = petugasId;
    data['proyek'] = proyek;
    data['unit'] = unit;
    data['unit_id'] = unitId;
    data['doc_date'] = docDate;
    data['resiko'] = resiko;
    data['kronologi'] = kronologi;
    data['dilakukan_tindakan'] = dilakukanTindakan;
    data['alasan'] = alasan;
    data['rincian_tindakan'] = rincianTindakan;
    data['saran'] = saran;
    data['tindak_lanjut'] = tindakLanjut;
    data['latitude'] = latitude;
    data['longitude'] = longitude;
    data['tindakan_tindak_lanjut'] = tindakanTindakLanjut;
    if (buktiFoto != null) {
      final v = buktiFoto;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['bukti_foto'] = arr0;
    }
    return data;
  }
}

class InspectionViewModel {
  /*
{
  "data": {
    "id": "01jyjeavnmb7wxd8rz3f043fcs",
    "created_at": "25/06/2025",
    "code": "006/F.INS-UA/K3L-MKP/I/1970",
    "type": "0",
    "kategori_name": "null",
    "kategori_id": "01jx5m22bpq176mbhn07g79eal",
    "doc_status": "0",
    "lokasi": "a",
    "petugas": "Admin K3",
    "petugas_id": "01jx5m236advexa306q0cyhqee",
    "proyek": "null",
    "unit": "Kantor Pusat",
    "unit_id": "01jx5m230nsp9r160yb6n59g46",
    "doc_date": "01/01/1970 00:00",
    "resiko": "a",
    "kronologi": "a",
    "dilakukan_tindakan": 1,
    "alasan": "null",
    "rincian_tindakan": "a",
    "saran": "a",
    "tindak_lanjut": 0,
    "longitude_latitude": "-122.08400000000002,37.421998333333335",
    "tindakan_tindak_lanjut": "",
    "bukti_foto": [
      {
        "id": "01jyjeavr4zpxq6tdxgkfwrf0d",
        "file": "http://10.0.2.2:8000/file_detail_inspeksi/1750818189_685b5d8d0de45.jpeg",
        "file_name": "1750818189_685b5d8d0de45.jpeg"
      }
    ]
  },
  "message": "Data berhasil diambil",
  "status": true
} 
*/

  InspectionViewModelData? data;
  String? message;
  bool? status;

  InspectionViewModel({this.data, this.message, this.status});
  InspectionViewModel.fromJson(Map<String, dynamic> json) {
    data =
        (json['data'] != null)
            ? InspectionViewModelData.fromJson(json['data'])
            : null;
    message = json['message']?.toString();
    status = json['status'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['data'] = this.data!.toJson();
      data['message'] = message;
    data['status'] = status;
    return data;
  }
}
