///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class InspectionModelData {
/*
{
  "id": "01jx6rjvymd7nd644z342aqc1j",
  "created_at": "08/06/2025",
  "code": "001/F.INS-NM/K3L-MKP/X/2025",
  "type": "0",
  "kategori_name": "Near Miss",
  "doc_status": "0",
  "lokasi": "serlokk",
  "petugas": "Admin K3",
  "doc_date": "04/10/2025 21:00"
} 
*/

  String? id;
  String? createdAt;
  String? code;
  String? type;
  String? kategoriName;
  String? docStatus;
  String? lokasi;
  String? petugas;
  String? docDate;

  InspectionModelData({
    this.id,
    this.createdAt,
    this.code,
    this.type,
    this.kategoriName,
    this.docStatus,
    this.lokasi,
    this.petugas,
    this.docDate,
  });
  InspectionModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    createdAt = json['created_at']?.toString();
    code = json['code']?.toString();
    type = json['type']?.toString();
    kategoriName = json['kategori_name']?.toString();
    docStatus = json['doc_status']?.toString();
    lokasi = json['lokasi']?.toString();
    petugas = json['petugas']?.toString();
    docDate = json['doc_date']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['created_at'] = createdAt;
    data['code'] = code;
    data['type'] = type;
    data['kategori_name'] = kategoriName;
    data['doc_status'] = docStatus;
    data['lokasi'] = lokasi;
    data['petugas'] = petugas;
    data['doc_date'] = docDate;
    return data;
  }
}

class InspectionModel {
/*
{
  "data": [
    {
      "id": "01jx6rjvymd7nd644z342aqc1j",
      "created_at": "08/06/2025",
      "code": "001/F.INS-NM/K3L-MKP/X/2025",
      "type": "0",
      "kategori_name": "Near Miss",
      "doc_status": "0",
      "lokasi": "serlokk",
      "petugas": "Admin K3",
      "doc_date": "04/10/2025 21:00"
    }
  ],
  "message": "Data berhasil diambil",
  "status": true
} 
*/

  List<InspectionModelData?>? data;
  String? message;
  bool? status;

  InspectionModel({
    this.data,
    this.message,
    this.status,
  });
  InspectionModel.fromJson(Map<String, dynamic> json) {
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <InspectionModelData>[];
  v.forEach((v) {
  arr0.add(InspectionModelData.fromJson(v));
  });
    this.data = arr0;
    }
    message = json['message']?.toString();
    status = json['status'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['data'] = arr0;
    }
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}
