import 'dart:convert';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class InspectionParam {
  /*
{
  "name": "hicun 3",
  "karyawan_id": "01jx5m236advexa306q0cyhqee",
  "type": "0",
  "proyek_name": "a",
  "unit_id": "01jx5m230nsp9r160yb6n59g46",
  "doc_date": "10/04/2025",
  "doc_time": "21:00",
  "kategori": "01jx5m22bpq176mbhn07g79eak",
  "resiko": "resikooo boss",
  "lokasi": "serlokk",
  "kronologi": "jadi gini",
  "action": "1",
  "alasan": "apa yaaaa",
  "saran": "nggak tauu",
  "rincian_tindakan": "awoooo",
  "foto": [
    "a"
  ]
} 
*/

  String? name;
  String? karyawanId;
  String? type;
  String? proyekName;
  String? unitId;
  String? docDate;
  String? docTime;
  String? kategori;
  String? resiko;
  String? lokasi;
  String? kronologi;
  String? action;
  String? alasan;
  String? saran;
  String? rincianTindakan;
  List<String?>? foto;

  InspectionParam({
    this.name,
    this.karyawanId,
    this.type,
    this.proyekName,
    this.unitId,
    this.docDate,
    this.docTime,
    this.kategori,
    this.resiko,
    this.lokasi,
    this.kronologi,
    this.action,
    this.alasan,
    this.saran,
    this.rincianTindakan,
    this.foto,
  });
  InspectionParam.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    karyawanId = json['karyawan_id']?.toString();
    type = json['type']?.toString();
    proyekName = json['proyek_name']?.toString();
    unitId = json['unit_id']?.toString();
    docDate = json['doc_date']?.toString();
    docTime = json['doc_time']?.toString();
    kategori = json['kategori']?.toString();
    resiko = json['resiko']?.toString();
    lokasi = json['lokasi']?.toString();
    kronologi = json['kronologi']?.toString();
    action = json['action']?.toString();
    alasan = json['alasan']?.toString();
    saran = json['saran']?.toString();
    rincianTindakan = json['rincian_tindakan']?.toString();
    if (json['foto'] != null) {
      final v = json['foto'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      foto = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (name != null) data['name'] = name;
    data['karyawan_id'] = karyawanId;
    data['type'] = type;
    data['proyek_name'] = proyekName;
    if (unitId != null) data['unit_id'] = unitId;
    data['doc_date'] = docDate;
    data['doc_time'] = docTime;
    data['kategori'] = kategori;
    data['resiko'] = resiko;
    data['lokasi'] = lokasi;
    data['kronologi'] = kronologi;
    data['action'] = action;
    data['alasan'] = alasan;
    data['saran'] = saran;
    data['rincian_tindakan'] = rincianTindakan;
    if (foto != null) {
      final v = foto;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['foto'] = jsonEncode(arr0);
    }
    return data;
  }
}
