///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class InspectionCategoryModelData {
/*
{
  "id": "01jx5m22bpq176mbhn07g79eak",
  "code": "NM",
  "name": "Near Miss",
  "description": "",
  "created_at": "2025-06-07T16:37:22.000000Z",
  "updated_at": "2025-06-07T16:37:22.000000Z",
  "deleted_at": "null"
} 
*/

  String? id;
  String? code;
  String? name;
  String? description;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  InspectionCategoryModelData({
    this.id,
    this.code,
    this.name,
    this.description,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  InspectionCategoryModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    code = json['code']?.toString();
    name = json['name']?.toString();
    description = json['description']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    deletedAt = json['deleted_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['code'] = code;
    data['name'] = name;
    data['description'] = description;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['deleted_at'] = deletedAt;
    return data;
  }
}

class InspectionCategoryModel {
/*
{
  "data": [
    {
      "id": "01jx5m22bpq176mbhn07g79eak",
      "code": "NM",
      "name": "Near Miss",
      "description": "",
      "created_at": "2025-06-07T16:37:22.000000Z",
      "updated_at": "2025-06-07T16:37:22.000000Z",
      "deleted_at": "null"
    }
  ],
  "message": "Data berhasil diambil",
  "status": true
} 
*/

  List<InspectionCategoryModelData?>? data;
  String? message;
  bool? status;

  InspectionCategoryModel({
    this.data,
    this.message,
    this.status,
  });
  InspectionCategoryModel.fromJson(Map<String, dynamic> json) {
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <InspectionCategoryModelData>[];
  v.forEach((v) {
  arr0.add(InspectionCategoryModelData.fromJson(v));
  });
    this.data = arr0;
    }
    message = json['message']?.toString();
    status = json['status'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['data'] = arr0;
    }
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}
