///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AgencySelectModelData {
  /*
{
  "id": "01jxefyyv6v1h4rkkemsa3f68m",
  "name": "PT Surya Citra Mandiri",
  "code": "INST001",
  "address": "Jl WR Supratman no 56 Sidoarjo"
} 
*/

  String? id;
  String? name;
  String? code;
  String? address;

  AgencySelectModelData({this.id, this.name, this.code, this.address});
  AgencySelectModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    code = json['code']?.toString();
    address = json['address']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['code'] = code;
    data['address'] = address;
    return data;
  }
}

class AgencySelectModel {
  /*
{
  "data": [
    {
      "id": "01jxefyyv6v1h4rkkemsa3f68m",
      "name": "PT Surya Citra Mandiri",
      "code": "INST001",
      "address": "Jl WR Supratman no 56 Sidoarjo"
    }
  ],
  "message": "Data berhasil diambil",
  "status": true
} 
*/

  List<AgencySelectModelData?>? data;
  String? message;
  bool? status;

  AgencySelectModel({this.data, this.message, this.status});
  AgencySelectModel.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <AgencySelectModelData>[];
      v.forEach((v) {
        arr0.add(AgencySelectModelData.fromJson(v));
      });
      this.data = arr0;
    }
    message = json['message']?.toString();
    status = json['status'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}
