///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class NotificationModelData {
/*
{
  "id": "01jx74qhaccvr0g7pbnewxar30",
  "title": "Approval Dokumen",
  "message": "Permintaan APD Nomor : 001/REQ/K3L-MKP/VI/2025",
  "is_read": false,
  "inspeksi_id": "null",
  "trs_request_id": "01jx74qh74045zrkdm0ccch8p0",
  "trs_good_issue_id": "null",
  "trs_good_receipt_id": "null",
  "trs_receive_material_id": "null",
  "trs_good_return_id": "null",
  "trs_stock_opname_id": "null",
  "user_creator_id": "01jx5m23g7gca309z0aq7ka4zc",
  "user_approve_id": "null",
  "tanggal_action": "2025-06-08 06:47:58",
  "status": "0",
  "created_at": "2025-06-08T06:47:58.000000Z",
  "updated_at": "2025-06-08T06:47:58.000000Z",
  "deleted_at": "null"
} 
*/

  String? id;
  String? title;
  String? message;
  bool? isRead;
  String? inspeksiId;
  String? trsRequestId;
  String? trsGoodIssueId;
  String? trsGoodReceiptId;
  String? trsReceiveMaterialId;
  String? trsGoodReturnId;
  String? trsStockOpnameId;
  String? userCreatorId;
  String? userApproveId;
  String? tanggalAction;
  String? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  NotificationModelData({
    this.id,
    this.title,
    this.message,
    this.isRead,
    this.inspeksiId,
    this.trsRequestId,
    this.trsGoodIssueId,
    this.trsGoodReceiptId,
    this.trsReceiveMaterialId,
    this.trsGoodReturnId,
    this.trsStockOpnameId,
    this.userCreatorId,
    this.userApproveId,
    this.tanggalAction,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  NotificationModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    title = json['title']?.toString();
    message = json['message']?.toString();
    isRead = json['is_read'];
    inspeksiId = json['inspeksi_id']?.toString();
    trsRequestId = json['trs_request_id']?.toString();
    trsGoodIssueId = json['trs_good_issue_id']?.toString();
    trsGoodReceiptId = json['trs_good_receipt_id']?.toString();
    trsReceiveMaterialId = json['trs_receive_material_id']?.toString();
    trsGoodReturnId = json['trs_good_return_id']?.toString();
    trsStockOpnameId = json['trs_stock_opname_id']?.toString();
    userCreatorId = json['user_creator_id']?.toString();
    userApproveId = json['user_approve_id']?.toString();
    tanggalAction = json['tanggal_action']?.toString();
    status = json['status']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    deletedAt = json['deleted_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['message'] = message;
    data['is_read'] = isRead;
    data['inspeksi_id'] = inspeksiId;
    data['trs_request_id'] = trsRequestId;
    data['trs_good_issue_id'] = trsGoodIssueId;
    data['trs_good_receipt_id'] = trsGoodReceiptId;
    data['trs_receive_material_id'] = trsReceiveMaterialId;
    data['trs_good_return_id'] = trsGoodReturnId;
    data['trs_stock_opname_id'] = trsStockOpnameId;
    data['user_creator_id'] = userCreatorId;
    data['user_approve_id'] = userApproveId;
    data['tanggal_action'] = tanggalAction;
    data['status'] = status;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['deleted_at'] = deletedAt;
    return data;
  }
}

class NotificationModel {
/*
{
  "data": [
    {
      "id": "01jx74qhaccvr0g7pbnewxar30",
      "title": "Approval Dokumen",
      "message": "Permintaan APD Nomor : 001/REQ/K3L-MKP/VI/2025",
      "is_read": false,
      "inspeksi_id": "null",
      "trs_request_id": "01jx74qh74045zrkdm0ccch8p0",
      "trs_good_issue_id": "null",
      "trs_good_receipt_id": "null",
      "trs_receive_material_id": "null",
      "trs_good_return_id": "null",
      "trs_stock_opname_id": "null",
      "user_creator_id": "01jx5m23g7gca309z0aq7ka4zc",
      "user_approve_id": "null",
      "tanggal_action": "2025-06-08 06:47:58",
      "status": "0",
      "created_at": "2025-06-08T06:47:58.000000Z",
      "updated_at": "2025-06-08T06:47:58.000000Z",
      "deleted_at": "null"
    }
  ],
  "message": "Data berhasil diambil",
  "status": true
} 
*/

  List<NotificationModelData?>? data;
  String? message;
  bool? status;

  NotificationModel({
    this.data,
    this.message,
    this.status,
  });
  NotificationModel.fromJson(Map<String, dynamic> json) {
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <NotificationModelData>[];
  v.forEach((v) {
  arr0.add(NotificationModelData.fromJson(v));
  });
    this.data = arr0;
    }
    message = json['message']?.toString();
    status = json['status'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['data'] = arr0;
    }
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}
