///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GuideModelData {
/*
{
  "id": "01jxcbqgy7tt7z33fc92azqsdy",
  "created_at": "01/01/1970",
  "nomor": "LAINLAIN/01",
  "judul": "LAIN-LAIN1",
  "kategori_name": "Lain-lain",
  "doc_status": "null",
  "file": "http://localhost:8000/pdf_pedoman_k3/1749540389_Biometric Face Recog CNN .pdf",
  "tanggal": "10/06/2025"
} 
*/

  String? id;
  String? createdAt;
  String? nomor;
  String? judul;
  String? kategoriName;
  String? docStatus;
  String? file;
  String? tanggal;

  GuideModelData({
    this.id,
    this.createdAt,
    this.nomor,
    this.judul,
    this.kategoriName,
    this.docStatus,
    this.file,
    this.tanggal,
  });
  GuideModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    createdAt = json['created_at']?.toString();
    nomor = json['nomor']?.toString();
    judul = json['judul']?.toString();
    kategoriName = json['kategori_name']?.toString();
    docStatus = json['doc_status']?.toString();
    file = json['file']?.toString();
    tanggal = json['tanggal']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['created_at'] = createdAt;
    data['nomor'] = nomor;
    data['judul'] = judul;
    data['kategori_name'] = kategoriName;
    data['doc_status'] = docStatus;
    data['file'] = file;
    data['tanggal'] = tanggal;
    return data;
  }
}

class GuideModel {
/*
{
  "data": [
    {
      "id": "01jxcbqgy7tt7z33fc92azqsdy",
      "created_at": "01/01/1970",
      "nomor": "LAINLAIN/01",
      "judul": "LAIN-LAIN1",
      "kategori_name": "Lain-lain",
      "doc_status": "null",
      "file": "http://localhost:8000/pdf_pedoman_k3/1749540389_Biometric Face Recog CNN .pdf",
      "tanggal": "10/06/2025"
    }
  ],
  "message": "Data berhasil diambil",
  "status": true
} 
*/

  List<GuideModelData?>? data;
  String? message;
  bool? status;

  GuideModel({
    this.data,
    this.message,
    this.status,
  });
  GuideModel.fromJson(Map<String, dynamic> json) {
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <GuideModelData>[];
  v.forEach((v) {
  arr0.add(GuideModelData.fromJson(v));
  });
    this.data = arr0;
    }
    message = json['message']?.toString();
    status = json['status'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['data'] = arr0;
    }
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}
