///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ApdReturnParamDataApdRtn {
  /*
{
  "id": "01jwbfjgzb6z87mwgnxvf3315p",
  "qty": 1
} 
*/

  String? id;
  String? code;
  String? name;
  int? qty;
  int? receivedQty;

  ApdReturnParamDataApdRtn({
    this.id,
    this.code,
    this.name,
    this.qty,
    this.receivedQty,
  });
  ApdReturnParamDataApdRtn.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    qty = json['qty']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['qty'] = qty;
    return data;
  }
}

class ApdReturnParam {
  /*
{
  "doc_date": "2025-04-21 00:00:00",
  "request_id": "01jx74qh74045zrkdm0ccch8p0",
  "pengeluaran_id": "01jx74qh74045zrkdm0ccch8p0",
  "description": "wiwok",
  "data_apd_rtn": [
    {
      "id": "01jwbfjgzb6z87mwgnxvf3315p",
      "qty": 1
    }
  ],
  "bukti_foto": "data:image/jpeg;base64",
  "ttd_foto": "data:image/jpeg;base64",
  "action": "draft"
} 
*/

  String? docDate;
  String? requestId;
  String? pengeluaranId;
  String? description;
  List<ApdReturnParamDataApdRtn?>? dataApdRtn;
  String? buktiFoto;
  String? ttdFoto;
  String? action;

  ApdReturnParam({
    this.docDate,
    this.requestId,
    this.pengeluaranId,
    this.description,
    this.dataApdRtn,
    this.buktiFoto,
    this.ttdFoto,
    this.action,
  });
  ApdReturnParam.fromJson(Map<String, dynamic> json) {
    docDate = json['doc_date']?.toString();
    requestId = json['request_id']?.toString();
    pengeluaranId = json['pengeluaran_id']?.toString();
    description = json['description']?.toString();
    if (json['data_apd_rtn'] != null) {
      final v = json['data_apd_rtn'];
      final arr0 = <ApdReturnParamDataApdRtn>[];
      v.forEach((v) {
        arr0.add(ApdReturnParamDataApdRtn.fromJson(v));
      });
      dataApdRtn = arr0;
    }
    buktiFoto = json['bukti_foto']?.toString();
    ttdFoto = json['ttd_foto']?.toString();
    action = json['action']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['doc_date'] = docDate;
    data['request_id'] = requestId;
    data['pengeluaran_id'] = pengeluaranId;
    data['description'] = description;
    if (dataApdRtn != null) {
      final v = dataApdRtn;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data_apd_rtn'] = arr0;
    }
    data['bukti_foto'] = buktiFoto;
    data['ttd_foto'] = ttdFoto;
    data['action'] = action;
    return data;
  }
}
