///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ApdReturnModelData {
  /*
{
  "id": "01jy0gf1qn41ne4xn2f6tyqk52",
  "doc_date": "18/06/2025",
  "code": "000/GR/K3L-MKP/VI/2025",
  "request_code": "032/REQ/K3L-MKP/VI/2025",
  "pengeluaran_code": "abc",
  "vendor_name": "VENDOR A",
  "deskripsi": "yy",
  "status": "Draft",
  "unit_name": "Kantor Pusat"
} 
*/

  String? id;
  String? docDate;
  String? code;
  String? requestCode;
  String? pengeluaranCode;
  String? vendorName;
  String? deskripsi;
  String? status;
  String? unitName;

  ApdReturnModelData({
    this.id,
    this.docDate,
    this.code,
    this.requestCode,
    this.pengeluaranCode,
    this.vendorName,
    this.deskripsi,
    this.status,
    this.unitName,
  });
  ApdReturnModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    docDate = json['doc_date']?.toString();
    code = json['code']?.toString();
    requestCode = json['request_code']?.toString();
    pengeluaranCode = json['pengeluaran_code']?.toString();
    vendorName = json['vendor_name']?.toString();
    deskripsi = json['deskripsi']?.toString();
    status = json['status']?.toString();
    unitName = json['unit_name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['doc_date'] = docDate;
    data['code'] = code;
    data['request_code'] = requestCode;
    data['pengeluaran_code'] = pengeluaranCode;
    data['vendor_name'] = vendorName;
    data['deskripsi'] = deskripsi;
    data['status'] = status;
    data['unit_name'] = unitName;
    return data;
  }
}

class ApdReturnModel {
  /*
{
  "data": [
    {
      "id": "01jy0gf1qn41ne4xn2f6tyqk52",
      "doc_date": "18/06/2025",
      "code": "000/GR/K3L-MKP/VI/2025",
      "request_code": "032/REQ/K3L-MKP/VI/2025",
      "pengeluaran_code": "abc",
      "vendor_name": "VENDOR A",
      "deskripsi": "yy",
      "status": "Draft",
      "unit_name": "Kantor Pusat"
    }
  ],
  "message": "Data berhasil diambil",
  "status": true
} 
*/

  List<ApdReturnModelData?>? data;
  String? message;
  bool? status;

  ApdReturnModel({this.data, this.message, this.status});
  ApdReturnModel.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <ApdReturnModelData>[];
      v.forEach((v) {
        arr0.add(ApdReturnModelData.fromJson(v));
      });
      this.data = arr0;
    }
    message = json['message']?.toString();
    status = json['status'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}
