///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ApdReturnViewModelDataDaftarPengeluaran {
/*
{
  "id": "01jxa02pj1n64sm9200zy56n9e",
  "apd_id": "01jx6tpxkwghf6gp62sq27ng64",
  "apd_name": "SEPATU APD",
  "qty": 1
} 
*/

  String? id;
  String? apdId;
  String? apdName;
  int? qty;

  ApdReturnViewModelDataDaftarPengeluaran({
    this.id,
    this.apdId,
    this.apdName,
    this.qty,
  });
  ApdReturnViewModelDataDaftarPengeluaran.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    apdId = json['apd_id']?.toString();
    apdName = json['apd_name']?.toString();
    qty = json['qty']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['apd_id'] = apdId;
    data['apd_name'] = apdName;
    data['qty'] = qty;
    return data;
  }
}

class ApdReturnViewModelData {
/*
{
  "id": "01jxa02phyyzjz5v51zxwpthsw",
  "created_at": "09/06/2025",
  "code": "000/GR/K3L-MKP/VI/2025",
  "vendor_name": "VENDOR A",
  "doc_status": "0",
  "description": "testpengembalianbaru",
  "doc_date": "09/06/2025 00:00",
  "permintaan_id": "01jx74qh74045zrkdm0ccch8p0",
  "pengeluaran_id": "01jx74qh74045zrkdm0ccch8p0",
  "daftar_pengeluaran": [
    {
      "id": "01jxa02pj1n64sm9200zy56n9e",
      "apd_id": "01jx6tpxkwghf6gp62sq27ng64",
      "apd_name": "SEPATU APD",
      "qty": 1
    }
  ]
} 
*/

  String? id;
  String? createdAt;
  String? code;
  String? vendorName;
  String? docStatus;
  String? description;
  String? docDate;
  String? permintaanId;
  String? pengeluaranId;
  List<ApdReturnViewModelDataDaftarPengeluaran?>? daftarPengeluaran;

  ApdReturnViewModelData({
    this.id,
    this.createdAt,
    this.code,
    this.vendorName,
    this.docStatus,
    this.description,
    this.docDate,
    this.permintaanId,
    this.pengeluaranId,
    this.daftarPengeluaran,
  });
  ApdReturnViewModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    createdAt = json['created_at']?.toString();
    code = json['code']?.toString();
    vendorName = json['vendor_name']?.toString();
    docStatus = json['doc_status']?.toString();
    description = json['description']?.toString();
    docDate = json['doc_date']?.toString();
    permintaanId = json['permintaan_id']?.toString();
    pengeluaranId = json['pengeluaran_id']?.toString();
  if (json['daftar_pengeluaran'] != null) {
  final v = json['daftar_pengeluaran'];
  final arr0 = <ApdReturnViewModelDataDaftarPengeluaran>[];
  v.forEach((v) {
  arr0.add(ApdReturnViewModelDataDaftarPengeluaran.fromJson(v));
  });
    daftarPengeluaran = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['created_at'] = createdAt;
    data['code'] = code;
    data['vendor_name'] = vendorName;
    data['doc_status'] = docStatus;
    data['description'] = description;
    data['doc_date'] = docDate;
    data['permintaan_id'] = permintaanId;
    data['pengeluaran_id'] = pengeluaranId;
    if (daftarPengeluaran != null) {
      final v = daftarPengeluaran;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['daftar_pengeluaran'] = arr0;
    }
    return data;
  }
}

class ApdReturnViewModel {
/*
{
  "data": {
    "id": "01jxa02phyyzjz5v51zxwpthsw",
    "created_at": "09/06/2025",
    "code": "000/GR/K3L-MKP/VI/2025",
    "vendor_name": "VENDOR A",
    "doc_status": "0",
    "description": "testpengembalianbaru",
    "doc_date": "09/06/2025 00:00",
    "permintaan_id": "01jx74qh74045zrkdm0ccch8p0",
    "pengeluaran_id": "01jx74qh74045zrkdm0ccch8p0",
    "daftar_pengeluaran": [
      {
        "id": "01jxa02pj1n64sm9200zy56n9e",
        "apd_id": "01jx6tpxkwghf6gp62sq27ng64",
        "apd_name": "SEPATU APD",
        "qty": 1
      }
    ]
  },
  "message": "Data berhasil diambil",
  "status": true
} 
*/

  ApdReturnViewModelData? data;
  String? message;
  bool? status;

  ApdReturnViewModel({
    this.data,
    this.message,
    this.status,
  });
  ApdReturnViewModel.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null) ? ApdReturnViewModelData.fromJson(json['data']) : null;
    message = json['message']?.toString();
    status = json['status'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}
