///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ApdReturnViewModelDataDaftarFoto {
  /*
{
  "id": "01jxbz2ywmredmqf15qc4mz3ze",
  "file": "http://localhost:8000/file_bukti_foto_pengembalian/file_bukti_foto_pengembalian/1749527133_6847aa5d1210f.jpeg",
  "filename": "1749527133_6847aa5d1210f.jpeg"
} 
*/

  String? id;
  String? file;
  String? filename;

  ApdReturnViewModelDataDaftarFoto({this.id, this.file, this.filename});
  ApdReturnViewModelDataDaftarFoto.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    file = json['file']?.toString();
    filename = json['filename']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['file'] = file;
    data['filename'] = filename;
    return data;
  }
}

class ApdReturnViewModelDataDaftarPengeluaran {
  /*
{
  "id": "01jxbz2ywck175yfyt5abhvtrc",
  "apd_id": "01jx6tpxkwghf6gp62sq27ng64",
  "apd_name": "SEPATU APD",
  "qty": 1,
  "code": "APD-000/WOM"
} 
*/

  String? id;
  String? apdId;
  String? apdName;
  int? qtyJumlah;
  String? qtySisa;
  int? qtyDikembalikan;
  String? code;
  String? warna;
  String? ukuranBaju;
  String? ukuranCelana;
  String? ukuranSepatu;
  String? jenisSepatu;

  ApdReturnViewModelDataDaftarPengeluaran({
    this.id,
    this.apdId,
    this.apdName,
    this.qtyJumlah,
    this.qtySisa,
    this.qtyDikembalikan,
    this.code,
    this.warna,
    this.ukuranBaju,
    this.ukuranCelana,
    this.ukuranSepatu,
    this.jenisSepatu,
  });
  ApdReturnViewModelDataDaftarPengeluaran.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    apdId = json['apd_id']?.toString();
    apdName = json['apd_name']?.toString();
    qtyJumlah = json['qty']?.toInt();
    qtySisa = json['qty_sisa']?.toString();
    qtyDikembalikan = json['qty_dikembalikan']?.toInt();
    code = json['code']?.toString();
    warna = json['warna']?.toString();
    ukuranBaju = json['ukuran_baju']?.toString();
    ukuranCelana = json['ukuran_celana']?.toString();
    ukuranSepatu = json['ukuran_sepatu']?.toString();
    jenisSepatu = json['jenis_sepatu']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['apd_id'] = apdId;
    data['apd_name'] = apdName;
    data['qty'] = qtyJumlah;
    data['qty_sisa'] = qtySisa;
    data['qty_dikembalikan'] = qtyDikembalikan;
    data['code'] = code;
    data['warna'] = warna;
    data['ukuran_baju'] = ukuranBaju;
    data['ukuran_celana'] = ukuranCelana;
    data['ukuran_sepatu'] = ukuranSepatu;
    data['jenis_sepatu'] = jenisSepatu;
    return data;
  }
}

class ApdReturnViewModelData {
  /*
{
  "id": "01jxbz2yw90n3tg7b1xvvn6t2q",
  "created_at": "10/06/2025",
  "code": "000/GR/K3L-MKP/VI/2025",
  "vendor_name": "VENDOR A",
  "doc_status": "0",
  "description": "testpengembalianbaru4",
  "doc_date": "10/06/2025 00:00",
  "permintaan_id": "01jx74qh74045zrkdm0ccch8p0",
  "unit_name": "Kantor Pusat",
  "permintaan_code": "001/REQ/K3L-MKP/VI/2025",
  "permintaan_date": "03/06/2025",
  "pengeluaran_id": "01jx74qh74045zrkdm0ccch8p0",
  "pengeluaran_code": "abc",
  "pengeluaran_date": "06/08/2025",
  "ttd_file": "http://localhost:8000/file_ttd_pengembalian",
  "ttd_name": "null",
  "daftar_pengeluaran": [
    {
      "id": "01jxbz2ywck175yfyt5abhvtrc",
      "apd_id": "01jx6tpxkwghf6gp62sq27ng64",
      "apd_name": "SEPATU APD",
      "qty": 1,
      "code": "APD-000/WOM"
    }
  ],
  "daftar_foto": [
    {
      "id": "01jxbz2ywmredmqf15qc4mz3ze",
      "file": "http://localhost:8000/file_bukti_foto_pengembalian/file_bukti_foto_pengembalian/1749527133_6847aa5d1210f.jpeg",
      "filename": "1749527133_6847aa5d1210f.jpeg"
    }
  ]
} 
*/

  String? id;
  String? createdAt;
  String? code;
  String? vendorName;
  String? docStatus;
  String? description;
  String? docDate;
  String? permintaanId;
  String? unitName;
  String? permintaanCode;
  String? permintaanDate;
  String? pengeluaranId;
  String? pengeluaranCode;
  String? pengeluaranDate;
  String? ttdFile;
  String? ttdName;
  String? latitude;
  String? longitude;
  List<ApdReturnViewModelDataDaftarPengeluaran?>? daftarPengeluaran;
  List<ApdReturnViewModelDataDaftarFoto?>? daftarFoto;

  ApdReturnViewModelData({
    this.id,
    this.createdAt,
    this.code,
    this.vendorName,
    this.docStatus,
    this.description,
    this.docDate,
    this.permintaanId,
    this.unitName,
    this.permintaanCode,
    this.permintaanDate,
    this.pengeluaranId,
    this.pengeluaranCode,
    this.pengeluaranDate,
    this.ttdFile,
    this.ttdName,
    this.latitude,
    this.longitude,
    this.daftarPengeluaran,
    this.daftarFoto,
  });
  ApdReturnViewModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    createdAt = json['created_at']?.toString();
    code = json['code']?.toString();
    vendorName = json['vendor_name']?.toString();
    docStatus = json['doc_status']?.toString();
    description = json['description']?.toString();
    docDate = json['doc_date']?.toString();
    permintaanId = json['permintaan_id']?.toString();
    unitName = json['unit_name']?.toString();
    permintaanCode = json['permintaan_code']?.toString();
    permintaanDate = json['permintaan_date']?.toString();
    pengeluaranId = json['pengeluaran_id']?.toString();
    pengeluaranCode = json['pengeluaran_code']?.toString();
    pengeluaranDate = json['pengeluaran_date']?.toString();
    ttdFile = json['ttd_file']?.toString();
    ttdName = json['ttd_name']?.toString();
    latitude = json['latitude']?.toString();
    longitude = json['longitude']?.toString();
    if (json['daftar_pengeluaran'] != null) {
      final v = json['daftar_pengeluaran'];
      final arr0 = <ApdReturnViewModelDataDaftarPengeluaran>[];
      v.forEach((v) {
        arr0.add(ApdReturnViewModelDataDaftarPengeluaran.fromJson(v));
      });
      daftarPengeluaran = arr0;
    }
    if (json['daftar_foto'] != null) {
      final v = json['daftar_foto'];
      final arr0 = <ApdReturnViewModelDataDaftarFoto>[];
      v.forEach((v) {
        arr0.add(ApdReturnViewModelDataDaftarFoto.fromJson(v));
      });
      daftarFoto = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['created_at'] = createdAt;
    data['code'] = code;
    data['vendor_name'] = vendorName;
    data['doc_status'] = docStatus;
    data['description'] = description;
    data['doc_date'] = docDate;
    data['permintaan_id'] = permintaanId;
    data['unit_name'] = unitName;
    data['permintaan_code'] = permintaanCode;
    data['permintaan_date'] = permintaanDate;
    data['pengeluaran_id'] = pengeluaranId;
    data['pengeluaran_code'] = pengeluaranCode;
    data['pengeluaran_date'] = pengeluaranDate;
    data['ttd_file'] = ttdFile;
    data['ttd_name'] = ttdName;
    data['latitude'] = latitude;
    data['longitude'] = longitude;
    if (daftarPengeluaran != null) {
      final v = daftarPengeluaran;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['daftar_pengeluaran'] = arr0;
    }
    if (daftarFoto != null) {
      final v = daftarFoto;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['daftar_foto'] = arr0;
    }
    return data;
  }
}

class ApdReturnViewModel {
  /*
{
  "data": {
    "id": "01jxbz2yw90n3tg7b1xvvn6t2q",
    "created_at": "10/06/2025",
    "code": "000/GR/K3L-MKP/VI/2025",
    "vendor_name": "VENDOR A",
    "doc_status": "0",
    "description": "testpengembalianbaru4",
    "doc_date": "10/06/2025 00:00",
    "permintaan_id": "01jx74qh74045zrkdm0ccch8p0",
    "unit_name": "Kantor Pusat",
    "permintaan_code": "001/REQ/K3L-MKP/VI/2025",
    "permintaan_date": "03/06/2025",
    "pengeluaran_id": "01jx74qh74045zrkdm0ccch8p0",
    "pengeluaran_code": "abc",
    "pengeluaran_date": "06/08/2025",
    "ttd_file": "http://localhost:8000/file_ttd_pengembalian",
    "ttd_name": "null",
    "daftar_pengeluaran": [
      {
        "id": "01jxbz2ywck175yfyt5abhvtrc",
        "apd_id": "01jx6tpxkwghf6gp62sq27ng64",
        "apd_name": "SEPATU APD",
        "qty": 1,
        "code": "APD-000/WOM"
      }
    ],
    "daftar_foto": [
      {
        "id": "01jxbz2ywmredmqf15qc4mz3ze",
        "file": "http://localhost:8000/file_bukti_foto_pengembalian/file_bukti_foto_pengembalian/1749527133_6847aa5d1210f.jpeg",
        "filename": "1749527133_6847aa5d1210f.jpeg"
      }
    ]
  },
  "message": "Data berhasil diambil",
  "status": true
} 
*/

  ApdReturnViewModelData? data;
  String? message;
  bool? status;

  ApdReturnViewModel({this.data, this.message, this.status});
  ApdReturnViewModel.fromJson(Map<String, dynamic> json) {
    data =
        (json['data'] != null)
            ? ApdReturnViewModelData.fromJson(json['data'])
            : null;
    message = json['message']?.toString();
    status = json['status'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}
